### ISSUE TITLE
Can't get past title

### ISSUE THREAD

**Issue by TobyReid1998** [whateverusername0/VRTRAKILL#1]
Once I load into the game I'm just falling down the red elevator shaft forever, and there is no menu for me to interact with. I am running this on a quest 2 with virtual desktop which I don't think is the issue since I'm still loading into the game.

**Comment by whateverusername0** [comment]
have you tried turning around?

**Comment by TobyReid1998** [comment]
> have you tried turning around? (physically, without using controller turning)

that worked lmao thank you

**Comment by whateverusername0** [comment]
should've left a note about it lol
