### ISSUE TITLE
[Feature Request] Height problems

### ISSUE THREAD

**Issue by Susknight** [whateverusername0/VRTRAKILL#105]
I have never touched steam vr until recently, im short and the weapons are massive with no fix. I have went to common problems and tried everything there, didnt fix it, my guardian boundary is set correctly last time i checked.

How to reproduce:
No known way to fix nor reproduce

Other info:
Quest 2
Intermediate software if using quest link
Vrtrakill version: 0.15

Notes:
This seems to happen as the user(me) may not be tall enough for the mod to correctly work, this may cause some problems for shorter people like me(5'8) and V1s height doesnt match mine if this isn't the case tell me. Ill see if theres anything i can do but for now i have to play like im really short and my arms are gigantic.

**Comment by whateverusername0** [comment]
well i'm not planning on adding height calibration any time soon...
doesn't mean that short people have to suffer, well, later on, so i'll figure smh out, just don't expect it rolling out as fast as possible.

**Comment by Susknight** [comment]
Ok good to know ill be able to actually play the mod without height issues soon (hopefully) although i did see some success in changing my guardian boundary floor slightly lower so it isnt as bad

**Comment by whateverusername0** [comment]
eh should be fixed in 0.17, by "fixed" i mean it has a player size calibration now
