### ISSUE TITLE
[BUG] NameHere

### ISSUE THREAD

**Issue by unlimintedpower** [whateverusername0/VRTRAKILL#106]
**Describe the bug**
I can't use the "punch/parry" function.

**Steps to Reproduce**
1. Load in
2. Press trigger
3. Nothing happens

**Expected behavior**
Punch

**Real behavior**
Nothing

**Other info:**
 - Headset: Oculus Quest 1
 - Intermediate software : Oculus Link
 - VRTRAKILL Version [e.g. 0.15]

**Additional context**
I tried changing the bind to see if it was my controller, but it still doesn't work.

**Comment by whateverusername0** [comment]
if you press punch and do nothing ofc it won't work. hold the trigger and fling your arm in the direction of the thing you want to demolish. simple

**Comment by unlimintedpower** [comment]
I will try that thanks

**Comment by whateverusername0** [comment]
i presume it works now
