### ISSUE TITLE
[Feature Request] Better weapon selection 

### ISSUE THREAD

**Issue by SpaikoTrapsu** [whateverusername0/VRTRAKILL#107]
Ultrakill is a game massively centered on the interactions between weapons, as such, quickly and reliably swapping between weapons and variations is essential for the game to flow, and this is something currently lacking, scrolling through them does work, as well as the weapon wheel but they are both too slow, the wheel itself considerably breaking the flow of the game, making those sick ass combos harder.

My suggestion would be implementing a more physical method of picking your firepower, the simple solution would be a menu similar to Alyx's or HL2VR. Another possibility that would make it even cooler would be holster slots, in other words specific points on the avatar's body where you can pick different weapons, such as the hip for the revolver, shoulder for rocket launcher, chest for shotgun, etc, but this would obviously be a lot more convoluted to work with.

Also, please add more controller models to make it more immersive. I can provide them myself, i'm a 3d artist with access to the same or similar modeling/texturing tools used by the UK team, and i'm willing to contribute some sick stylized controllers for the project.

**Comment by whateverusername0** [comment]
i don't want to reinvent the wheel, because everything works out of the box and i want to keep it as vanilla as possible (as in base game mechanics) (spectator camera doesn't count. bet nobody uses it anyways except me)
and, regarding controller models, hit me up with some in a pull request :) (the current oq2c model is in unity project/assets/controllers/something)

**Comment by SpaikoTrapsu** [comment]
I get your point, but just as it was done with HL2, the selector would be just a 3d menu that sends the number key input corresponding to the chosen weapon, i believe it would feel more natural on the gameplay, but overall, it's up to you.
I'll get to work on the models and send them whenever possible
