### ISSUE TITLE
[BUG] Error spam and Missing left hand

### ISSUE THREAD

**Issue by InvertedCrink** [whateverusername0/VRTRAKILL#109]
**Describe the bug**
Once the game launched in VR, The console was filled with errors and, after starting the first level, I was unable to punch.
After trying to turn off "Enable movement-based punching" in the config file, my left hand became invisible in levels (not in the menu) and it remained this way even after turning this back on (The arm remains visible, just the hand disappears)

**Steps to Reproduce**
1. Install the game, BepInEx (5.4.21) and install the mod (0.15 with 0.15.1 patch)
2. Run the game and enter a level
3. See errors and try to punch (and possibly a missing left hand)

**Expected behaviour**
To be able to punch and have my left hand

**Real behaviour**
Unable to punch and lacking my left hand

**Media**
![20231004211456_1](https://github.com/whateverusername0/VRTRAKILL/assets/54511013/9f46a48b-3160-48a3-a6de-3f6110728d2b)
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/12807815/LogOutput.log)
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/12807810/Player.log)

**Other info:**
 - Headset: Valve Index
 - Intermediate software: N/A
 - VRTRAKILL Version: 0.15.1

**Additional context**
I have attempted getting a patched version of 'globalgamemanagers' (and removing the VR patcher) as mentioned in the common issues.

**Comment by whateverusername0** [comment]
try checking your steamvr input bindings (including poses) and/or copying your inputs from ultrakill settings to the config. the message displays an empty space because the button or the key leading to that button doesn't exist.

and regarding errors on the startup... it's always been there :/ i couldn't care enough to fix that because it didn't bring any problems _yet_.

**Comment by InvertedCrink** [comment]
I should be able to give these suggestions a go tomorrow; I'll get back to you sometime then.

**Comment by InvertedCrink** [comment]
Ah, it would seem that steam automatically bound both triggers to shoot; I am now able to punch.
After some testing around it seems that the missing hand is caused by having movement based punching disabled.

**Comment by whateverusername0** [comment]
so... everything works? cool :)
