### ISSUE TITLE
[Feature Request, I guess] Type Me

### ISSUE THREAD

**Issue by xzxADIxzx** [whateverusername0/VRTRAKILL#110]
**Describe the solution you'd like**
Do everything for me

**Describe alternatives you've considered**
There are no alternatives here

**Additional context**
I want to sleep rn 😴 

> 1.x.x: Mods compatibility (JAKET, ~~ultraballing~~, etc.) (dab me up xzxADIxzx)

Shall you give me a virtual reality helmet so that I can add support for your mod, or will you do everything yourself, and I will have a well-deserved rest?

**Comment by whateverusername0** [comment]
😨damn ok
