### ISSUE TITLE
Game doesnt start in vr

### ISSUE THREAD

**Issue by realZeol** [whateverusername0/VRTRAKILL#111]
Game loads like it wasnt modded

I have downloaded the bepnienx and vrtrakill both the latest versions
Yes i followed the steps correctly
Yes i did the optional steps
Yes i tried without the optional steps
It doesnt work

Log output:
[Message:   BepInEx] BepInEx 5.4.22.0 - ULTRAKILL (01.10.2023 17:36:21)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [VRTRAKILL 0.15.1]
[Message:   BepInEx] Chainloader startup complete

when i open it using steam app it shows me that it will only be showing om the desktop and not on the vr
when i use the vr app it tells me to open it i theater mode
yes i have disabled theater mode

it just opens with normal ui
the bepinix works cuz it created folders and files and the mod also works it created the config file

my pc is very cursed
pls help

the config is set correctly

**Comment by whateverusername0** [comment]
are you sure you set everything up correctly? check twice, thrice if needed

**Comment by realZeol** [comment]
yes i did it correcty
and i reinstalled it

**Comment by realZeol** [comment]
when i add the non steam game (optional way) it gets me stuck in the next up screen
at the same time ultrakill loads normally without vr

**Comment by whateverusername0** [comment]
i don't see the vrpatcher being loaded and doing it's stuff. perhaps you don't have a patched version of gamemanagers and that's why it starts in non-vr more

**Comment by realZeol** [comment]
thanks will check

**Comment by realZeol** [comment]
vr patcher failed
will try to find a solution

**Comment by realZeol** [comment]
whose vr patcher should i use

**Comment by realZeol** [comment]
works
