### ISSUE TITLE
Punch still doesn't work

### ISSUE THREAD

**Issue by unlimintedpower** [whateverusername0/VRTRAKILL#115]
Describe the bug
I can't use the "punch/parry" function.

Steps to Reproduce

Load in
Hold trigger
Fling arm around in front of that breakable wood in the intro
Nothing is happening
( I also tried parrying some projectiles, but that didn't work either)
Expected behavior
Punch

Real behavior
Nothing

Other info:

Headset: Oculus Quest 1
Intermediate software: Oculus Link
VRTRAKILL Version [e.g. 0.15]
Additional context
I tried changing the bind to see if it was my controller, but it still doesn't work.

**Comment by whateverusername0** [comment]
what do you see in the tutorial? open 0-1 and check if an action is present there, if not - something is wrong with your steamvr bindings. also double check if your config keyboard binds are the same as in ultrakill, it's important to keep them mirrored.

**Comment by unlimintedpower** [comment]
I synced up my bindings with my desktop version and made sure that I was on the default SteamVR bindings, but it still doesn't work. I don't know what you mean in the first sentence though.

**Comment by whateverusername0** [comment]
you shouldn't be on default steamvr bindings? you should be on custom set named "VRTRAKILL Defaults {controller-name}"

**Comment by unlimintedpower** [comment]
Yeah, that's what I meant. If I had the wrong bindings, then none of them would work, but only the punch doesn't work.

**Comment by whateverusername0** [comment]
do you have "Shoot" or "Punch" on the left controller trigger binding?

**Comment by whateverusername0** [comment]
hey to speed things up better hmu on discord (it's on the main repo's page)

**Comment by whateverusername0** [comment]
you didn't hit me up on discord :(
