### ISSUE TITLE
game keeps alt tabbing during gameplay, opening task manager during swordsmachine fight

### ISSUE THREAD

**Issue by Orifan1** [whateverusername0/VRTRAKILL#117]
no idea what the hell is causing this. no idea how to reproduce other than just like... go fight SM yourself. specifically on a fresh save file. 0-3. just the piercer, marksman, and i guess core eject since you pick that up from SM. no sharpshooter

**Comment by whateverusername0** [comment]
bro, do you have, like, alt and tab binded to sum controls in ultrakill?
everything works flawlessly. it's something on your side

**Comment by Orifan1** [comment]
standby. earlier i noticed there was a new version. currently trying to get that to work to see if that fixes the issue but the update instructions are a bit confusing. presently i have it booting with turning working in the main menu but the actual menu doesn't appear. 

but i dont remember altering the binds. additionally, that doesn't explain why its launching TASK MANAGER

**Comment by Orifan1** [comment]
got it to work aaaand god damnit. at least no TM so far. is there a log file i can send?

**Comment by whateverusername0** [comment]
> that doesn't explain why its launching TASK MANAGER

it does WHAT?
you can find all the log files locations in the bug issue template

**Comment by whateverusername0** [comment]
aaand i think you got _mail_ on your pc. i recommend fully scanning it with malwarebytes or smh, because alt tabbing and opening task manager is **not** included in mod's behavior

**Comment by Orifan1** [comment]
malwarebytes came up clean. windows defender full scan is... going to take a while. in the meantime i attempted to recreate the bug. it did not open TM or the start menu this time but i quit as soon as the first instance of it happening happened so that you can just cut right to the end to see it.
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/12851915/LogOutput.log)
windows defender estimates ~6 hours left in the scan. im gonna go finally play the new sonic frontiers update while i wait for it to finish

**Comment by Orifan1** [comment]
windows defender detected cheatengine but that's it. removed it anyway, will try later to see if that fixed it

**Comment by Orifan1** [comment]
shit actually i just had a thought. what if all this is happening because of my taskbar settings? this doesn't account for why its specifically task manager and the start menu that opens but it does explain the alt tabbing and task manager opening (i have it pinned to my task bar)
i have it set so that my taskbar automatically hides itself. is it possible that im somehow (probably from throwing my arms down in disappointment when i die) moving the cursor down to un-hide the taskbar, DESPITE the game being fullscreen?

**Comment by whateverusername0** [comment]
nah the mod has nothing to do with the cursor. your issue is paranormal istg

**Comment by Orifan1** [comment]
nothing in the logs?

damn. im gonna have to actually install a screencorder for this huh

**Comment by whateverusername0** [comment]
hey to speed things up better hmu on discord (it's on the main repo's page)

**Comment by Orifan1** [comment]
i dont think im in the right discord server. is "VRTRAKILL HQ" the one?

**Comment by whateverusername0** [comment]
yes

**Comment by whateverusername0** [comment]
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/f16c0165-d3fb-4a29-b876-9e2d56015ecc)
