### ISSUE TITLE
[BUG] rocket launcher doesnt aim properly

### ISSUE THREAD

**Issue by Ultra-Ballin** [whateverusername0/VRTRAKILL#118]
Describe the bug:
whenever i try to use the rocket launcher the weapon points heavily to the left of where i am actually aiming

Steps to Reproduce:
holding rocket launcher

Expected behavior:
rocket launcher points forward where my arm is facing like other weapons

Real behavior:
rocket launcher point to the left of where my arm is facing
Media:
https://github.com/whateverusername0/VRTRAKILL/assets/147779214/3bc29616-c97a-4b82-b44f-372ece2e332a

Other info:
 - Headset: Oculus Quest 1
 - Intermediate software Oculus Link
 - VRTRAKILL Version 0.15.2

**Additional context**
sometimes if i fully outstretch my arm pointing directly forward it works as expected for a second or two

**Comment by whateverusername0** [comment]
it's not a bug, it's a feature :)
the crosshair even aligns with it's aiming direction

**Comment by Ultra-Ballin** [comment]
why even have bug reports if you are just going to ignore the issue and lie whenever somebody has a problem

**Comment by whateverusername0** [comment]
it ain't a bug i'm telling you. it was made this way on purpose.

**Comment by whateverusername0** [comment]
i'm also not changing the way it works.
somebody made a fork where the rocket launcher is "fixed", you can go check it out.

**Comment by Ultra-Ballin** [comment]
ah my bad i dont use this site a lot

**Comment by TheRyeGuyWhoWillNowDie** [comment]
FOR ANYONE ELSE HAVING THIS ISSUE, WHO WANTS THE ROCKET LAUNCHER TO WORK PROPERLY:
Go into the configuration, change the true on "Enable VRavatar" to false. The rocket launcher will now work like every other weapon.

**Comment by whateverusername0** [comment]
:(
