### ISSUE TITLE
the main menu doesn't work

### ISSUE THREAD

**Issue by Rowan9811** [whateverusername0/VRTRAKILL#12]
for whatever reason when I've ever get to the main menu the ui for the main menu just doesn't load
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/11355445/LogOutput.log)
![ULTRAKILL_hN9cJus75d](https://user-images.githubusercontent.com/77900870/235201150-6865ec1d-e741-4d5d-bcb7-66c0bc24a17e.png)

**Comment by whateverusername0** [comment]
1. this log file tells nothing
2. try turning around (physically, without using controllers)

**Comment by Rowan9811** [comment]
for some reason I have to load Unity Explorer for it to work

**Comment by whateverusername0** [comment]
holy shit what
