### ISSUE TITLE
[BUG] revolver and feedbacker disappearing

### ISSUE THREAD

**Issue by ak-sergeev** [whateverusername0/VRTRAKILL#122]
Describe the bug The meshes of hands and revolver parts disappear if looking up too far, even though they're still clearly in my fov

Steps to Reproduce

use the base revolver and feedbacker
tilt head upward while keeping hands at the same height
look down without moving head
weapons parts disappear while still in view
Expected behavior weapon stays visible

Real behavior weapon parts disappears

Other info:

- Headset: Oculus Quest 3
- Intermediate software: Virtual Desktop
- VRTRAKILL Version: 0.17

I saw that users had already reported this bug and it's been fixed, but for some reason it appeared again

**Comment by whateverusername0** [comment]
the problem lies in models not being rendered offscreen. that should be an easy fix, nothing could possibly go wrong
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/e1ee8628-f0ef-4325-a918-1521d03df154)

**Comment by whateverusername0** [comment]
should be fixed in bleeding-edge
if you wanna play it, build it yourself
