### ISSUE TITLE
[Feature Request] Add a Discord or some way to talk about the mod or bugs you're having

### ISSUE THREAD

**Issue by Acenthus** [whateverusername0/VRTRAKILL#123]
Not a ton to say here, I just feel like a community would take some of the pressure off of you when it comes to bugs people are having that have an easy fix. Like for example my punch and other things weren't working and I couldn't find anything on it, I reset my binds to default in-game and it fixed so I didn't need to report it. That and also I wanted to say the mod is actually insanely well made and translates shockingly well to VR, so I kinda wish there was a better place to do that rather than over the github issues tab. That on top of giving people a place to talk about it along with just ultrakill would be pretty nice.

**Comment by whateverusername0** [comment]
the discord's already there. on the main repo page. blue clickable bold text "Discord".
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/f6f395ea-17f3-4c5f-83f1-fcfb32d368f4)

**Comment by Acenthus** [comment]
I may be a bit acoustic

**Comment by whateverusername0** [comment]
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/d469904b-cb48-46d9-b7e0-3f992ffb979e)
