### ISSUE TITLE
[BUG] Shoot and Dash

### ISSUE THREAD

**Issue by undertaule** [whateverusername0/VRTRAKILL#124]
**Describe the bug**:
On Oculus quest 2. Whenever I play the game, When I'm starting to shoot it dash at the same time even if I changed the binding to two different places, the dash is connected to the shooting and I can't get rid of it.

**Steps to Reproduce**:
1. Launch the game on Oculus quest 2 (With Oculus link)
2. Select any level
3. Shoot
4. it will dash

**Expected behavior**:
I wanted to have the dash and shoot at different binding.

**Real behavior**:
It dashes when I shoot.

**Other info: **
 - Headset: [Oculus Quest 2]
 - Intermediate software (Oculus Link)
 - VRTRAKILL Version [e.g. 0.17]

**Additional context**
I tried to fix it by changing the binding a lot of time, Even if I put the dash and delete the shoot from my binding, It will not dash, Only shooting can make me dash

**Comment by whateverusername0** [comment]
did you rebind only controllers? check your keyboard ones, sync them with config ones, etc. etc.
try harder
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/dad4f2d7-a29d-49b3-9bcb-fa2a88ee8b3e)

**Comment by whateverusername0** [comment]
ig you solved it
