### ISSUE TITLE
Menu Fails to Load + Error Spam

### ISSUE THREAD

**Issue by SomewhatMinty** [whateverusername0/VRTRAKILL#125]
After launching the game via SteamVR, I was greeted by the main menu elevator environment, and without any options to interact, aside from rotating. No indicators of where my controllers are, no menu in front of me. I tried the general troubleshooting options listed in the common issues section, and tinkered around with it myself. No change.

**Steps to Reproduce**:
1. Download and install BepInEx 5.4.22
2. Download and install the latest version of VRTRAKILL via the listed .zip file.
3. Load game via SteamVR, fall down endless elevator forever, and see no menu nor interaction options aside from turning via right thumbstick.

**Expected behavior**:
I was expecting to see a menu to interact with, or be able to open a menu with one of the buttons on my Index controllers.

**Real behavior**:
No menu was present, regardless of what buttons I pushed. Turning via right thumbstick works. BepInEx log spammed with a multitude of errors.

**Media**:
(Hands are being held in front of face, headset is looking in default direction.)

[https://cdn.discordapp.com/attachments/903053668130095169/1180025301770702858/20231130215822_1.jpg?ex=657beb33&is=65697633&hm=a81eeba7d7d80aba960e291ed4a08678b9f07a502cfd1983c3fb12fb9913baa0&](url)

Some of the logs that were spit out. The logs were alternating between several variations at rapid speed.

[https://cdn.discordapp.com/attachments/903053668130095169/1180026125443936266/image.png?ex=657bebf8&is=656976f8&hm=1dbcb6c7a933254fffb90e974a456a427975c41316206932889a73030d6fe5f5&](url)

[https://cdn.discordapp.com/attachments/903053668130095169/1180026415828185168/image.png?ex=657bec3d&is=6569773d&hm=ae1020a5320e8f6449cce0951224e13937adf2a9b7908bdec7f852e9816cb727&](url)

**Other info:**
 - Headset: Valve Index
 - Intermediate software: SteamVR, OVR Advanced Settings
 - VRTRAKILL Version: 0.17

**Additional context**
I am new to modding ULTRAKILL, however, I have made sure that I followed the usual process to the best of my ability. I have modded other games before, and have a vague idea of what I'm doing.

**Comment by whateverusername0** [comment]
that's cool and all, but your screenshots don't tell much. pls send the latest player.log file from LocalLow appdata /Hakita/ULTRAKILL
also check if it has the error spam in the middle or at the end (if you played normal ultrakill after that, if you didn't - checking shouldn't be necessary)

**Comment by SomewhatMinty** [comment]
> that's cool and all, but your screenshots don't tell much. pls send the latest player.log file from LocalLow appdata /Hakita/ULTRAKILL also check if it has the error spam in the middle or at the end (if you played normal ultrakill after that, if you didn't - checking shouldn't be necessary)

Ah, so that's what the instructions were referring to. My bad, first time doing an in-depth bug report. I'll attach the log in the next message... as soon as I figure out why my computer has a stroke trying to read the file.

**Comment by SomewhatMinty** [comment]
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/13543737/Player.log)

**Comment by whateverusername0** [comment]
are you sure you have 0.17? the log says you got 0.16 and it failed to load custom assets. better reinstall the entire thing n lmk if it worked

**Comment by SomewhatMinty** [comment]
Reinstalled. Didn't fix it, but the .log output seems to have changed.
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/13642909/Player.log)

**Comment by whateverusername0** [comment]
there is 100% something wrong with your assets file in the mod folder.
