### ISSUE TITLE
Punch doesn't work + error spam in log

### ISSUE THREAD

**Issue by NikitaVorons** [whateverusername0/VRTRAKILL#126]
**Steps to Reproduce**:
1. Download and install BepInEx 5.4.22.0
2. Download and install the latest version of VRTRAKILL via the listed .zip
3. Launch game via SteamVR  and  launch prelude and can't punch in tutorial

**Expected behavior**:
I was excepting a but the game does not respond to holding with the left trigger
**Real behavior**:
I can't punch,i try tutorial

**Media**:
http://www.mediafire.com/file/0r17j71mykyle8e/LogOutput.log

**Other info:**
 - Headset: Oculus Quest 2
 - Oculus Link
 - VRTRAKILL Version 0.17

**Comment by whateverusername0** [comment]
did you visit the tutorial level?

**Comment by NikitaVorons** [comment]
yes,i hold left trigger on oculus touch and and nothing happens except vibration after pressing and hold the left trigger, the game does not react in any way

**Comment by SvineruS** [comment]
same, left trigger doesn't perform hand attack, but it works for minecart speed control

**Comment by NikitaVorons** [comment]
OK. then which button to punch

**Comment by AnthonySoda** [comment]
If it helps, I'm having the same issue, and the error message is talking about the "Look rotation viewing vector" being zero. Does this mean it can't track where we're looking, and therefore can't send a punch to where we want it?

Exact error: MissingMethodException: void SubtitleController.DisplaySubtitle(string,UnityEngine.AudioSource)     Stack trace:

**Comment by whateverusername0** [comment]
14c update fucked the mod up a bit

**Comment by Wild-Dog** [comment]
Having the same issue now. I remember I fixed it somehow, can't remember for the life of me.

**Comment by whateverusername0** [comment]
oh yeah the fix is out it's in the discord server :P
sorry, couldn't get myself to post it on github, will do asap

**Comment by whateverusername0** [comment]
uploaded the release, everything should be fixed now.
