### ISSUE TITLE
[Feature Request] (index) Binding for 'next weapon'

### ISSUE THREAD

**Issue by jasperfirecai2** [whateverusername0/VRTRAKILL#127]
**Is your feature request related to a problem? Please describe.**
On index controllers, it's currently not very possible to switch weapons besides quickswap, swap variation and weapon wheel. The only place you are able to bind 'next weapon' is weapon scroll via touchpad scroll, which is not very usable because it's a velocity based scroll (so you overshoot all the time. this is steam's problem, not yours.).

**Describe the solution you'd like**
A binding that acts as a weapon scroll forward/backward, that you can assign to any 'button' type binding in SteamVR.

**Describe alternatives you've considered**
I've considered binding 'equip weapon 1, 2, 3' etc. but i don't see there being a feasible way to fit that all on index controllers.

**Additional context**
-

**Comment by whateverusername0** [comment]
sure, will do

**Comment by whateverusername0** [comment]
done
