### ISSUE TITLE
[BUG] Crashing at 7-1 boss

### ISSUE THREAD

**Issue by pararara1** [whateverusername0/VRTRAKILL#132]
**Describe the bug**:
After fighting the boss for like 10 minutes, performance starts degrading and eventually the game freezes.

**Media**:

Bepin terminal printout
[bosscrash.log](https://github.com/whateverusername0/VRTRAKILL/files/13747952/bosscrash.log)

**Other info:**
 - Headset: WMR

**Comment by whateverusername0** [comment]
shouldn't be vrtrakill problem
