### ISSUE TITLE
[BUG] Controls do not do anything ingame.

### ISSUE THREAD

**Issue by brianmartinm** [whateverusername0/VRTRAKILL#133]
Before reporting anything, see [Common issues](https://github.com/whateverusername0/VRTRAKILL/wiki/Common-issues)  

**Describe the bug**:
After installing, I launched the game and I couldn't interact with the main menu to start playing, additionally, after a while of waiting, the entire background went black.
**Steps to Reproduce**:
1. Install everything as best as you can
2. Run the game
3. Find yourself unable to interact with the main menu.

**Expected behavior**:
I expected to be able to interact with the main menu.

**Real behavior**:
I was not able to interact with the main menu

**Media**:
Add screenshots / videos to help explain your problem (unnecessary, but **highly recommended**).  

https://github.com/whateverusername0/VRTRAKILL/assets/78971159/47d253c8-9416-4f09-a37e-f9a5a9571f0e

Also please add the logs so that i can get a better understanding of the problem. There should be no personal information stored in them, so don't hesitate :)  
The logs are located in "**ULTRAKILL/BepInEx/LogOutput.log**" and
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/13760079/LogOutput.log)
 "**&
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/13760085/Player.log)
USERPROFILE%\AppData\LocalLow\Hakita\ULTRAKILL\Player.log**"

**Other info:**
 - Headset: Oculus Rift S
 - Intermediate software: None
 - VRTRAKILL Version: 0.18

**Additional context**
I was able to rotate, and I have tried fixing it myself via looking at the common issues and such but nothing in there worked. I also tried installing a different version of bepinex to see if I was just being stupid and I wasn't, I had the correct installation.

**Comment by whateverusername0** [comment]
looks like something is wrong with the game, since the mod doesn't do anything with PlayerInput fields. do you have other mods installed? did you reinstall the whole game before modding it?

**Comment by brianmartinm** [comment]
i do not have any other mods installed, this is my first time trying my hand at anything to modify ultrakill, and i did reinstall the whole game before modding it.

**Comment by Trollingm** [comment]
same bug occurring here, interacting works if a left click occurs on the desktop. does not work in game

**Comment by whateverusername0** [comment]
> same bug occurring here, interacting works if a left click occurs on the desktop. does not work in game

because your ultrakill window should be active, on top, etc.

**Comment by Trollingm** [comment]
we have ensured the tab is active and on top

**Comment by whateverusername0** [comment]
idk then, check your ultrakill, steamvr and vrtrakill bindings
