### ISSUE TITLE
Game keeps crashing in 7-1

### ISSUE THREAD

**Issue by Nosynose326** [whateverusername0/VRTRAKILL#134]
**Describe the bug**:
It seams like it only crashes when you don't beat the boss at the end of 7-1

**Steps to Reproduce**:
1. Get to the boss fight
2. Die [like 5 times idk]
3.then ( atlest for me) have the whole pc softlock and die

**Expected behavior**:
Not having pc die

**Real behavior**:
Pc dying 

**Media**:
NaN

**Other info:**
 - quest2 with virtual desktop 
 - VRTRAKILL Version newest build 

**Additional context**
Add any other context about the problem here. For example, did you try to fix it yourself? If yes, how?

**Comment by whateverusername0** [comment]
uhhh... sounds like a hardware issue
