### ISSUE TITLE
[BUG] v0.18 Difficulty picking up / Dropping off Skulls & Vibration Issue with Controllers

### ISSUE THREAD

**Issue by Sho0Fly** [whateverusername0/VRTRAKILL#135]
**Describe the bug**:
Difficulty picking up and dropping skull keys on any map. Hit box doesn't seem to be consistent when disabling movement based punching.

**Steps to Reproduce**:
1. In VRTRAKILL_Config.jason, change "Enable movement-based punching" to false, "Movement Multiplier" set to 1, "Enable VRAvatar" set to "False"
2. Launch game, go to any level with a skull keycard.
3. Attempt to grab skull. Skull will not be picked up and controllers will be constantly vibrating (at start of any level).
NOTE: This is prior to unlocking grappling hook. (First Act). Grappling hook works fine but only after you unlock it in the 2nd act.

**Expected behavior**:
Skull key is expected to be picked up. Controllers shouldn't be vibrating unless appropriate action is taken. Takes a lot of attempts fiddling around skull stand to pick up the skull wasting a lot of time.

**Real behavior**:
Nothing happens. Punch air and no skull key is picked up. Controllers are also constantly rumbling with no variation or reason.

**Media**:
Video of bug
https://youtube.com/shorts/gZ6Ltirx73U?si=8P-ttifEDvmnhFiy

[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/13789642/LogOutput.log)

[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/13789646/Player.log)

[Player-prev.log](https://github.com/whateverusername0/VRTRAKILL/files/13789649/Player-prev.log)

**Other info:**
 - Headset: Quest 3 
 - Intermediate software (if using Quest): Virtual Desktop using SteamVR
 - VRTRAKILL Version v0.18

**Additional context**
Skull keys are not able to be picked up easily. Constant vibration in controllers, have disabled vibration entirely in .json config to mitigate. 

Clean install of v0.18, no mods installed besides BepInEx 5.4.22.0 x64. Fresh start and save file in VR. 

Windows 11 Pro 64-bit
RTX 4070 ti
intel i9-10900k
64GB Ram

*Update: Looks like it is possible to pick up the skulls but I can't seem to easily recreate the position to pick them up. Sometimes it is right away, other times I have to go to the side, behind, or just get to the right distance + position to pick it up. Very unreliable and hard to reproduce a pick up.

**Update 2: This can be mitigated by using the grappling hook, however you don’t unlock that until later in the next Act.

**Comment by whateverusername0** [comment]
sorry, dunno why this happens 🤷‍♂️

**Comment by Sho0Fly** [comment]
Unsure as well, I can’t tell if it’s just luck or if it gets worse as time goes on. Only guess is the hit-box for punching (using  "Enable movement-based punching" to false) causes a drift overtime.

Using VD and no snap turn so maybe something goes funky in between levels.

**Comment by whateverusername0** [comment]
> causes a drift overtime

shouldn't do so, because in the game's source, you punch directly at where you look no matter what.
