### ISSUE TITLE
[Feature Request] Config option to make marksman coins eject from the right hand.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#138]
**Is your feature request related to a problem? Please describe.**
My problem is that, if i'm in the middle of combat and I need to parry/punch and toss a coin, given how much you will be moving the left hand to punch it can make the coin trajectory inconsistent with your revolver. 

**Describe the solution you'd like**
I remember really old builds of this included this, but that was because at the time fists were just attached to your face since controls for them weren't ready yet at the time.

**Describe alternatives you've considered**
Downgrading, both ultrakill and the mod, but that isn't exactly a *good* alternative given all the other lovely additions made to the game and mod over time.

**Additional context**
Trying to perform +FISTFUL OF DOLLAR is hard, lol.

**Comment by whateverusername0** [comment]
as far as i get it you're trying to coinpunch or just do ricoshots? ngl that's just a skill issue. it's also hard to perform in the base game too.

here's the coin being aligned to revolver's shooting direction, which means the trajectory _is_ consistent:
https://github.com/whateverusername0/VRTRAKILL/assets/113782077/20d60446-6360-4275-b17c-eb2535558904

and here's hyper absolutely busting it down railcoin style (might be unrelated):
https://medal.tv/games/ultrakill/clips/1mYpJMoWkV38oA

**Comment by Mr-Foxtrot** [comment]
Primarily focused on coin punching. I can do it reliably on desktop, same for shooting, it's just in VR it seems half the time I try and punch the coin I miss despite it appearing like I *should* hit it.

I can parry enemy projectiles just fine, shotgun parrying is a lil funky sometimes but works most of the time, it's coins though that seem super inconsistent when trying to punch.

**Comment by Mr-Foxtrot** [comment]
also that railcoin clip is awesome lol

**Comment by whateverusername0** [comment]
> punch the coin I miss despite it appearing like I should hit it

in ultrakill the coin has a small delay before becoming shootable/punchable, read on that if you want to.
anyways it'll just break the game logic, so i'm not adding it, sorry.
