### ISSUE TITLE
[Feature Request] Additional crosshair for left arm, to help with aiming the whiplash.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#139]
**Is your feature request related to a problem? Please describe.**
Unlike your right arm, the left doesn't have a crosshair. Normally understandable, since the left arm is primarily for punching: however the whiplash complicates things when you don't know exactly where it's gonna land.

**Describe the solution you'd like**
Simply duplicate the crosshair of the right arm, to the left arm.

**Describe alternatives you've considered**
You can get a feel for it over time, but that still isn't really a solution.

**Comment by whateverusername0** [comment]
this surely is frustrating, but walking with two crosshairs feels weird and you might confuse one with the other, do you have any ideas that could help solve that problem?

**Comment by Mr-Foxtrot** [comment]
You could potentially change the color or texture of the crosshair.

Right one being white = guns
Left one being blue/red/green depending on the arm = fists

If not that, another alternative is to allow lasers being drawn instead of a crosshair. They might not fit the style of the game but getting the two confused would be a lot harder than floating crosshairs.

**Comment by Mr-Foxtrot** [comment]
Risk of Rain 2 VR mod has lasers as an option for both hands and helps with aiming.

**Comment by whateverusername0** [comment]
> They might not fit the style of the game

exactly.

> Risk of Rain 2 VR mod has lasers as an option for both hands and helps with aiming.

eh.
adding a second crosshair/laser is still a bad design choice in my opinion, plus you get used to it, just like rocket launcher. not adding it, sorry
