### ISSUE TITLE
[BUG][VALVE INDEX] Wrong Swap Weapon Type bindings

### ISSUE THREAD

**Issue by OctaHeart** [whateverusername0/VRTRAKILL#14]
Hello! There is an issue with the Valve Index bindings. I made sure that the bindings do match exactly what they say in game and in Ultrakill_Config AND in the Steam VR bindings, but "Swap Weapon Variation" does not work, it seems to be bound to "Punch" (or "F") no matter what I set. I tried rebinding punch, but it's always taken as a left click as well.

**Other info:**
 - Valve Index
 -XSOverlay, Desktop+
 -0.8

**Comment by whateverusername0** [comment]
Hi. These bugs are being worked on right now. They'll be fixed in the next patch. I won't be closing this issue until i make sure that everything works correctly and release the patch.

**Comment by whateverusername0** [comment]
fixed in the next patch
