### ISSUE TITLE
[Feature Request] Make menu interaction globally support both hands instead of just the offhand.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#141]
**Is your feature request related to a problem? Please describe.**
Not really a problem per say, just a little strange you can only interact with the non-dominant hand and not the other one.

**Describe the solution you'd like**
Make the interaction ray apply to both hands instead of just the left one.

**Describe alternatives you've considered**
None, I can't think of any alternative for this than to just suck it up and deal with it lol.

**Comment by whateverusername0** [comment]
imo it would feel less logical, since in the base game you also interact with screens using only 1 hand, exception being the main menu, but changing it for a single screen? eh, sorry
