### ISSUE TITLE
Weapon Switching Not Working

### ISSUE THREAD

**Issue by Stoniac** [whateverusername0/VRTRAKILL#143]
**Describe the bug**:
None of the options to switch weapons actually switch weapons when inputted, with the exception of selecting specific weapon slots.

**Steps to Reproduce**:
1. Press button on Valve Index
2. Wait for V1 to switch weapons
3. Wait for V1 to switch weapons
4. Wait for V1 to switch weapons

**Expected behavior**:
The action described by the button mapping should be executed when the button it’s mapped to is pressed

**Real behavior**:
Nothing happen :(

**Media**:
None

<!-- Additional info:
 - Headset: Valve Index

**Comment by whateverusername0** [comment]
did you double check everything? binds, keybinds, etc.

**Comment by Stoniac** [comment]
> did you double check everything? binds, keybinds, etc.

No, but I just talked to my friend about it and he told me to do that. That was probably the issue. Although, would you be able to add a setting so that the weapon switching with next/prevweapon occurs on the first frame the button is pushed and not every frame when it’s pushed? (Input.GetKeyDown vs Input.GetKey should fix this)

**Comment by whateverusername0** [comment]
Input class does not work with steamvr action set, thus i can't

**Comment by Stoniac** [comment]
> Input class does not work with steamvr action set, thus i can't

I'm sure there's another way to do this. I was just giving an example. It would be really nice to have
