### ISSUE TITLE
[Feature Request] Adding mod to Thunderstore

### ISSUE THREAD

**Issue by WesCook** [whateverusername0/VRTRAKILL#144]
**Is your feature request related to a problem? Please describe.**
Currently, the mod installation steps require making direct changes to the install directory.  Modern modding ecosystems often hook into the install path instead to reduce data duplication and maintain clean installs.  This method is more resistant to updates, and will not create issues when Steam validates game files.

**Describe the solution you'd like**
r2ModMan is a popular mod launcher for Unity games that use BepInEx.   It pulls mods from the Thunderstore repository, for which Ultrakill [is already supported](https://thunderstore.io/c/ultrakill/).  Uploading VRTRAKILL to the Thunderstore would allow for easier and cleaner mod installation.

**Describe alternatives you've considered**
N/A

**Additional context**
I believe this installation method would be preferable for those that are already installing mods for Ultrakill or other Unity games.  The manual install method may still be preferred by some as it has fewer steps, though they are more technical in nature.

**Comment by whateverusername0** [comment]
nah. i would've added it months ago if not for my 🌟 _future plans_ 🌟.

**Comment by whateverusername0** [comment]
also thunderstore is related to overwolf, which i personally hate

**Comment by aetherwastake** [comment]
I mean fair but i think there would be less issues in the long run, no? Now im curious abt these future plans
