### ISSUE TITLE
[BUG] Config files aren't generating

### ISSUE THREAD

**Issue by gordonscrowbar2** [whateverusername0/VRTRAKILL#146]
Using the text and video tutorial, I have copied my ULTRAKILL folder. Gave it Bepinex 5.4.21 x64  which created it's files properly. The issue arises when I copy the VRTRAKILL folder into the game root. Even after running the game, no files are generated. I've tried doing it over to no avail.

**Comment by whateverusername0** [comment]
hmm seems like an installation issue. you sure everything is installed as it should be?
double check plugins folder

**Comment by gordonscrowbar2** [comment]
I fixed it by manually copying both files into the ULTRAKILL root folder. But I checked many times in the plugin folder several times and it wasn't there.

**Comment by lilbook55** [comment]
happened to me too

**Comment by lilbook55** [comment]
what files did you copy into the root folder?
