### ISSUE TITLE
[BUG] vrultrakill black screen and wont load

### ISSUE THREAD

**Issue by spidertron** [whateverusername0/VRTRAKILL#148]
**Describe the bug**:
the screen is black and doesn't boot up anything, mods are all uninstalled.  "error:index is outside bounds of array" "[error:unity log] spams> "missing field extension: field 'playerinput.fire1' not found"
**Steps to Reproduce**:
>start game
>error and black screen

**Expected behavior**:
>start game
>main menu

**Real behavior**:
>start game
>vr screen reads "waiting"
>"ultrakill.exe not responding"
![Screenshot 2024-01-22 004523](https://github.com/whateverusername0/VRTRAKILL/assets/50144553/076a661c-b873-4fa7-99a3-19a01e91f371)

**Media**:

[Message:   BepInEx] BepInEx 5.4.22.0 - ULTRAKILL (4/27/2023 12:39:34 AM)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] Loaded 1 patcher method from [VRPatcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   Console] Backing up 'E:\ULTRAKILL\ULTRAKILL_Data/globalgamemanagers'...
[Info   :   Console] Backup already exists.
[Info   :   Console] Begin epic conversion from ULTRAKILL to VRTRAKILL...
[Info   :   Console] Using ClassData file from 'E:\ULTRAKILL\BepInEx\patchers\classdata.tpk'
[Info   :   Console] Epic conversion from ULTRAKILL to VRTRAKILL is complete.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [VRPatcher.Patcher]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [VRTRAKILL 0.18.0]
[Info   : VRTRAKILL] Checking for updates...
[Error  : VRTRAKILL] Unable to check for updates!
[Error  : VRTRAKILL] Index was outside the bounds of the array.
[Info   : VRTRAKILL] Searching for compatible mods...
[Info   : VRTRAKILL] Finished searching for compatible mods.
[Message:   BepInEx] Chainloader startup complete

<!-- Additional info:
Quest 2 with virtual desktop

**Comment by spidertron** [comment]
![Screenshot 2024-01-22 004543](https://github.com/whateverusername0/VRTRAKILL/assets/50144553/2c564f94-9d68-41bf-8dff-895062c3f2f3)
![Screenshot 2024-01-22 004605](https://github.com/whateverusername0/VRTRAKILL/assets/50144553/eadae675-c9c3-488f-8c65-fa98a1adf839)

**Comment by whateverusername0** [comment]
yeah 14c update fucked it up
