### ISSUE TITLE
[BUG] Course of Corpse King Floor is stuck on screen

### ISSUE THREAD

**Issue by Prodgidy** [whateverusername0/VRTRAKILL#15]
The title says it all, the bottom floor on the skybox in "Court of the Corpse King" is stuck on the lower half of your view

To Reproduce: load that level

Expected Behavior: do i have to say?

Real Behavior: title and description says it all

Media: None

Other Info: Ver. 0.8, PCVR

**Comment by whateverusername0** [comment]
yeah i know about this issue. dunno how to fix it, but i'll let this sit here until i figure it out and fix it

**Comment by Prodgidy** [comment]
fair, also i couldnt figure out how to get the switch weapon iteration to work, i changed the binding on the config and changed the binding on the controller (to move the dash button) but it still no work :( could i get some guidance? thanks

**Comment by whateverusername0** [comment]
what exactly did you bind to where and what did you change in the config? weapon iteration works only on joysticks. also weapon wheel interaction will be rolling out in the next patch, so you could either wait or not change anything (kek).

**Comment by Prodgidy** [comment]
oh all good ill wait, i just changed the iteration to E since its default in the game

**Comment by whateverusername0** [comment]
oh man if you mean changing weapon variation then there's a problem in the config AGAIN and it'll 100% be fixed in the next patch

**Comment by whateverusername0** [comment]
The bug will be fixed in the next update
