### ISSUE TITLE
[BUG] Nearly all binds are non-functional

### ISSUE THREAD

**Issue by SCAbruh** [whateverusername0/VRTRAKILL#151]
**Describe the bug**:
Interacting with the ui requires clicking on the desktop, firing weapons doesn't work, the only actions I can perform are moving, turning, and pausing.

**Steps to Reproduce**:
Follow installation instructions of current version (0.19.1)
try to play game
game don't play right

**Expected behavior**:
Bindings as configured in SteamVR would function

**Real behavior**:
The only actions I can perform are moving, turning, and pausing.

**Media**:
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/14120286/LogOutput.log)
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/14120288/Player.log)

 - Headset: Quest Pro with Knuckles controllers via Steam Link

**Comment by whateverusername0** [comment]
yeah it's a known bug, i'll be dealing with it, for now downgrade to a version which doesn't include the feat of autofilling keybinds

**Comment by whateverusername0** [comment]
found a quick solution: reset every keybind and restart the game.
