### ISSUE TITLE
Punch still does not work on quest

### ISSUE THREAD

**Issue by AussieProot** [whateverusername0/VRTRAKILL#152]
**Describe the bug**:
punching and parrying does not work, but the sound still plays and you can still knuckle blast.

**Steps to Reproduce**:
1. pull trigger 
2. swing arm

**Expected behavior**:
Punch/parry/Knuckle blast

**Real behavior**:
Feedbacker: noise plays
Knuckleblaster: noise plays, explosion still fully works

**Media**:
upon double checking the logs it seems as if i've found an issue. apart from the normal startup stuff it just says:
"[Warning: VRTRAKILL] No arm found!" about 200 times. How do I find my arm?
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/14133761/LogOutput.log)

!-- Additional info:
 - Headset: Oculus Quest 2
 - Intermediate software: Oculus Link
rechecked bindings but the noise still plays so it isn't a controller or oculus link issue.
Also pulled a muscle while trying to parry so an accessibility option that removes the need to swing your arm would be great.
I know, I'm not very athletic but also I play ultrakill so what did you expect?

**Comment by whateverusername0** [comment]
yeah i'm workin on it

**Comment by whateverusername0** [comment]
what version are you on

**Comment by AussieProot** [comment]
0.18 because its completely non functional in 0.19 and 0.19.1.

**Comment by whateverusername0** [comment]
no it is, reset your uk keybinds and restart the game
