### ISSUE TITLE
[Feature Request] Controller Configuration

### ISSUE THREAD

**Issue by Br00klynShadow** [whateverusername0/VRTRAKILL#153]
**Is your feature request related to a problem? Please describe.**
The controls are frankly abysmal. Dash being on the left controller makes no sense, especially since the right controller has two ways to swap weapons which is unnecessary. Weapon swapping being on the right stick also sucks since you can very easily accidentally swap weapons while looking around. 

**Describe the solution you'd like**
Add a full control configuration file so it can be edited to best fit the user.

**Comment by whateverusername0** [comment]
uh... done!
https://steamcommunity.com/sharedfiles/filedetails/?id=2029205314
not _exactly_ the same but it's useful

**Comment by Br00klynShadow** [comment]
> uh... done! https://steamcommunity.com/sharedfiles/filedetails/?id=2029205314 not _exactly_ the same but it's useful

I suppose that works, thanks for the heads up. Id still recommend moving dash to the right controller.
