### ISSUE TITLE
[BUG] i do the instructions as told, but i get to step four and see no error in the console

### ISSUE THREAD

**Issue by DreamInSepsis** [whateverusername0/VRTRAKILL#154]
**Describe the bug**:
this could very well just be me missing something but uh, i put the general description in the title. it should be moderately easy to deduce what exactly went wrong 

**Steps to Reproduce**:
not known

**Expected behavior**:
an error that generates a new file appears in console

**Real behavior**:
<no error surfaces

 Additional info:
 - Headset: Samsung Odyssey 
 - Software: Mixed Reality

**Comment by whateverusername0** [comment]
you did sth wrong, check the dll in mod folder
