### ISSUE TITLE
[BUG] Infinite elevator

### ISSUE THREAD

**Issue by misheeee** [whateverusername0/VRTRAKILL#155]
**Describe the bug**:
When I open the game it opens steam vr then loads the intro and im stuck in a infinite elvetator falling with no menu options

**Steps to Reproduce**:
I have BepInEx installed (lastest version)
Ultrakill is on the lastest patch 14d
the vrpatcher is installed (ive used the CopyToGameRoot)
no mods beside vrtrakill are installed

**Expected behavior**:
i could see the menu and start the game

**Real behavior**:
infinite elevator falling and no menu or anthyng else
**Media**:

When I load the game it endlessly shows this error in console
![image](https://github.com/whateverusername0/VRTRAKILL/assets/161956644/4e304c42-c931-48f1-8a53-67b60b6c2c13)
and for some reason even tho i have the latest vrra kill version installed it says that i have 1.91.0
![image](https://github.com/whateverusername0/VRTRAKILL/assets/161956644/d50597f1-331c-4f4a-be89-37182a2c4343)
<!-- Additional info:
 - Headset: Oculus Quest 2
 - Oculus Air link
 - Steam Vr opened

**Comment by misheeee** [comment]
also i tried to delete my save file and start from the very beginning and it looks like im just very high?
![image](https://github.com/whateverusername0/VRTRAKILL/assets/161956644/88a9c746-acd8-4a1e-9193-6af58a5874e2)

**Comment by whateverusername0** [comment]
> also i tried to delete my save file and start from the very beginning and it looks like im just very high?
> 
> ![image](https://github.com/whateverusername0/VRTRAKILL/assets/161956644/88a9c746-acd8-4a1e-9193-6af58a5874e2)
> 
> 

eh that's an intro elevator thing

**Comment by whateverusername0** [comment]
something is defo wrong, prepare unity latest player.log located in locallow app data and bepinex latest log

**Comment by misheeee** [comment]
Whoopsies i guess i have had an outdated version of uktrakill all works now sorry!
