### ISSUE TITLE
[BUG] no text?

### ISSUE THREAD

**Issue by taeman72** [whateverusername0/VRTRAKILL#156]
**Describe the bug**:

even though the ui and the game act fine, none of the text is showing on the menus and style meter
**Steps to Reproduce**:

unknown
**Expected behavior**:

there should be text on all of the ui
**Real behavior**:

there isnt any text on the ui
**Media**:

![image](https://github.com/whateverusername0/VRTRAKILL/assets/164202000/987d456f-4433-42a3-b05e-443d873b35ae)

**Additional info**:
 - Headset: oculus rift s
 - software: steam vr

**Comment by whateverusername0** [comment]
you closed it but didn't even leave a solution🥺😭

**Comment by taeman72** [comment]
Yeah, my bad. all i did was reinstall the game and the mod was working again
