### ISSUE TITLE
Jumping gives you less heigh on Valve Index.

### ISSUE THREAD

**Issue by OctaHeart** [whateverusername0/VRTRAKILL#16]
https://youtu.be/X-zIfZoo0JY I don't know what else to say other than I can't jump high at all. I'm using the default binding for jump which is Left Stick Click.

Valve Index
Desktop+, XSOverlay,
0.8

**Comment by whateverusername0** [comment]
it might be because of the patch 13b and i haven't updated yet. i'll take a look what i can do about it, because atm if i remove the code that divides your jumping power by 2 you'll be able to jump over buildings.

**Comment by whateverusername0** [comment]
i was wrong. it's an index problem. i'll add an option in the config to not override jump power. after i release the next update please lmk if everything works so i can close this issue

**Comment by OctaHeart** [comment]
Will do!

**Comment by OctaHeart** [comment]
This does seem to be fixed, (if there's any height I'm missing I'm not able to tell), but there's a new bug with the sliding being really really short as well. I can get a video of this if you need it?
