### ISSUE TITLE
[BUG]can't do things

### ISSUE THREAD

**Issue by Bigboyman36** [whateverusername0/VRTRAKILL#160]
I can't party, jump, dash, slide, shoot the revolver or any of its alts, or, most importantly, walk. I need help, like a lot

**Comment by whateverusername0** [comment]
ikr. it's an update issue and i'm working on it. the hardest thing to port is the alt shotgun atm.
if you really need a fresh build you can go to #stuff in the discord server, get the .dll outta here and replace it yourself in BepInEx/plugins/VRTRAKILL.
thanks

**Comment by Bigboyman36** [comment]
So what youre saying is the zip file isn't working and you use the DLL file?

**Comment by whateverusername0** [comment]
with the latest update you can do things

**Comment by Bigboyman36** [comment]
Got it, thanks, really appreciated.

**Comment by Bigboyman36** [comment]
Also, I noticed that there's a new update, do I put both files in the ULTRAKILL file?
