### ISSUE TITLE
[BUG] game not launching in steamvr

### ISSUE THREAD

**Issue by ABitGlitchy** [whateverusername0/VRTRAKILL#166]
**Describe the bug**:
 
Whenever I open the game I am greeted with errors in the BepInEx console stating that unity cannot be initialized and the game launches in vr mode, but not in steamvr.

**Steps to Reproduce**:

1. Follow download instructions correctly
2. Run game

**Expected behavior**:

Game opens correctly in steamvr

**Real behavior**:

Game opens to the main menu, not launching or being detected by steamvr
**Media**:

[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/15241808/LogOutput.log)

Headset: Oculus Quest 2, Oculus Link via cable, steamvr
Tried re-installing vrtrakill version multiple times as well as bepinex to make sure everything was the correct version

**Comment by whateverusername0** [comment]
vr initialization failed with the error 310. there's something wrong with that steamvr of yours, or so i think
try doing whatever i found on the internet https://www.youtube.com/watch?v=clSNWGoa3H8 . might work, but not guaranteed to.

**Comment by ABitGlitchy** [comment]
my steamvr not being set to the beta mode seemed to be the issue
