### ISSUE TITLE
[Feature Request] please for the love of god just put this on Thunderstore or something else that can do this all for me

### ISSUE THREAD

**Issue by TarnishedCain** [whateverusername0/VRTRAKILL#167]
**Is your feature request related to a problem? Please describe.**
ive tried downloading this mod 10 times and all have failed. i followed every instruction too

**Describe the solution you'd like**
put it on thunderstore or another auto mod download site

**Describe alternatives you've considered**
NexusMods

**Comment by whateverusername0** [comment]
nuh uh!
