### ISSUE TITLE
[BUG] Weapon wheel not weapon wheeling

### ISSUE THREAD

**Issue by LioPrime** [whateverusername0/VRTRAKILL#168]
**Describe the bug**:
Weapon wheel not working

**Steps to Reproduce**:
Simply open the weapon wheel

**Expected behavior**:
Opening the weapon wheel, then selecting the weapon.

**Real behavior**:
Opening the weapon wheel, and then it just doesnt let me select one, and I cant close it either.

**Additional info**:
 - Headset: Quest 3
 - Intermediate software: Steam Link

**Comment by whateverusername0** [comment]
real

**Comment by whateverusername0** [comment]
now it does, i think
