### ISSUE TITLE
[BUG] Bounce vent things not bouncing

### ISSUE THREAD

**Issue by LioPrime** [whateverusername0/VRTRAKILL#169]
**Describe the bug**:
When stepping on a bouncepad in 7-4 (and maybe other levels im not sure if other levels have them) it wont do anything

**Steps to Reproduce**:
Step on a bounce vent thing pad whatever

**Expected behavior**:
Bouncing

**Real behavior**:
Not bouncing

Additional info:
 - Headset: Quest 3
 - Intermediate software: Steam link

**Comment by whateverusername0** [comment]
i already fixed it but the release is not on github but on our discord server 🤷 i'll release it here soon enough

**Comment by LioPrime** [comment]
aghh

**Comment by whateverusername0** [comment]
now they do
