### ISSUE TITLE
Dashing gives you less distanc on Valve Index.

### ISSUE THREAD

**Issue by OctaHeart** [whateverusername0/VRTRAKILL#19]
https://youtu.be/CcpaYOlEU8s I don't know what else to say other than I can't dash far at all. I'm using a changed binding for jump which is my right controller's A button.

Valve Index
Desktop+, XSOverlay,
0.81

**Comment by OctaHeart** [comment]
Also, a side note, can you change the default controller binding for dash to not be on the left controller? Since it makes it impossible to directional dash unless you press the button with your right hand which will _definitely_ screw up your aim.

**Comment by whateverusername0** [comment]
by any chance are you walking slowly? this might be the root of your problem

**Comment by OctaHeart** [comment]
The walk seems to be normal speed to me.

**Comment by OctaHeart** [comment]
Okay no, the walk speed's definitely off, I recorded me walking from one end of sandbox to the other from the wall of the building to the wall under the staircase, and ULTRAKILL reaches the wall 3 seconds before VRTRAKILL does.

**Comment by whateverusername0** [comment]
movement uses joystick axis. i think something's on your side is off, better check your steamvr settings.. index.. stuff.. whatever?

**Comment by OctaHeart** [comment]
Just checked, and no, it's working. [I even took a video with my controller test panel overlayed onto it](https://youtu.be/jpeAgRwUkLM) (Dash is on right controller, that's why nothing changes on the display when I dash). My controllers are working fine, I promise you.

**Comment by whateverusername0** [comment]
you're either the one who has everything working correctly, or something IS wrong. anyways i added a new option in the config to not override movement AT ALL. It'll be coming in the next patch. Friendly reminder that this issue stays open until you say that everything works :)

**Comment by whateverusername0** [comment]
did it work?

**Comment by OctaHeart** [comment]
It seems to be working mostly, It seems that I'm short by a fraction of the normal dash length (a dash goes across 2 barriers side by side, in VRTRAKILL, it seems to be going across 1.8 barriers), so it's either me not having working eyes, or it is off barely still. I don't know if there's a spot in the game though that I can test *exactly* 3 dashes back to back and tell how far I went, since the barriers I typically use to test might get displaced if there are too many of them.

**Comment by whateverusername0** [comment]
if it works it works :)
