### ISSUE TITLE
Issues making controls

### ISSUE THREAD

**Issue by pogcat09** [whateverusername0/VRTRAKILL#2]
Hello, I am having issues configuring the controls for the oculus touch controllers, I try to add controls by adding lines in the json. If possible, I would love if there was a premade controls json with buttons like jump, dash, and regular movement. Any help is appreciated though. Thanks!

**Comment by whateverusername0** [comment]
there are already premade steamvr controller bindings (VRTRAKILL Defaults) and default keybinds in the json. what exactly is the problem? bindings don't work? keybinds in the json not set correctly? i need more details

**Comment by whateverusername0** [comment]
my guy i'm gonna leave this issue open for another 2 days if you won't answer i'll be closing it

**Comment by whateverusername0** [comment]
that's it

**Comment by Prodgidy** [comment]
ok so i know that im pretty much necroposting and i know that itll be annoying for me to comment especially now but, i think they mean that they're having issues changing the controls that are already there

**Comment by whateverusername0** [comment]
there's still not enough details, meaning i literally cannot help even if i wanted to ("changing lines in the json") :(.

**Comment by Prodgidy** [comment]
the only other thing i can give is an example, that being if you wanted to change the jump button from left joystick to right joystick, how would you go about it
i dunno man its difficult to explain unless your wanting like console bits or somethin
