### ISSUE TITLE
[BUG] weird movement after dying

### ISSUE THREAD

**Issue by Skanler** [whateverusername0/VRTRAKILL#25]
**Describe the bug**
after dying and respawning, you get stuck in this really weird floating movement, only way to clear it is to restart the mission/load a new level

**Steps to Reproduce**
1. die
2. respawn
3. move around

**Expected behavior**
moving normally

**Real behavior**
floating movement

**Media**
https://user-images.githubusercontent.com/83680873/236591369-c66a4c8a-3c0e-43ed-82a4-f721f554e312.mp4

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software (if using Quest) Virtual Desktop
 -  - VRTRAKILL Version 0.82.

**Additional context**
also can barely jump, slide, or dash

**Comment by whateverusername0** [comment]
ik about this issue. it might happen when you die in the air or on a slope (or a couple times). honestly idk how to fix that, but i'll see what i can do about it.

for now the only solution is restarting mission :(

**Comment by Skanler** [comment]
could it be because its the same button as the whiplash? i have no idea what im talking about im just wondering

**Comment by whateverusername0** [comment]
it shouldn't be. it might have something to do with death behavior (when player gets tossed around after dying, can be clearly seen in leviathan fight)

**Comment by whateverusername0** [comment]
will be fixed in the next update, lmk when everything works

**Comment by whateverusername0** [comment]
should be fixed.
reopen the issue if the bug's still there
