### ISSUE TITLE
[enhancement] ability to scale the game

### ISSUE THREAD

**Issue by Skanler** [whateverusername0/VRTRAKILL#26]
i didnt see a template for enhancements so i just made a blank issue

its probably because im a little short but the game seemed super big to me when i first booted it up, i dont know how much flexibility you have with the mod, but it would be nice to have this

also i did try the scaling in steamvr but it just broke virtual desktop and ultrakill?? 
it doesnt save for some reason either

**Comment by whateverusername0** [comment]
scaling the game is pretty much impossible. the only thing i can think of is scaling the character.

being too short is not a problem. for example in flatscreen v1's height is at the level of minos' pelvis (🐔)

also scaling in steamvr? is that a thing?

**Comment by elliotttate** [comment]
Are you in the Flat2VR.com Discord? There's multiple ways to solve this and we can help you in there. Raicuparta did an interesting workaround for The Stanley Parable as the whole world was half size for some reason. Some of our mods with VRIK use some other techniques.

**Comment by whateverusername0** [comment]
i don't think i'll be doing that. perhaps later. idk. soon enough. maybe.
