### ISSUE TITLE
[Enhancement] Option to attach weapon wheel to right hand.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#29]
The current implementation of the weapon wheel is alright, but an option to attach it to the right hand instead of the center of the screen and to make it use the right controller analog stick instead of the left would probably work a lot better.

**Comment by whateverusername0** [comment]
will be added in the next update, lmk when everything works

**Comment by whateverusername0** [comment]
added in the next update (tested it myself)
