### ISSUE TITLE
VRTRAKILL is not launching - VRPatcher.Patcher: System.OverflowException

### ISSUE THREAD

**Issue by Kedjik** [whateverusername0/VRTRAKILL#30]
I tried so many things but i cant get this working. I tried with pirated ULTRAKILL and steam ULTRAKILL both gave me the same errors. Im launching VRTRAKILL in SteamVR but its says launching but its stucks at SteamVR void it never starts in VR.

Errors : 
First it gives `[Error  :   BepInEx] Failed to run Initializer of VRPatcher.Patcher: System.OverflowException`
Then it spams `[Error  : Unity Log] Could not find match for direction: in` for a while.

Full logs from console : [Link](https://cdn.discordapp.com/attachments/747949114666385419/1104499456897994773/Console.txt)
Pastebin link if you dont wanna download the txt : [pastebin](https://pastebin.com/gJTAS2ka)

**Other info:**
 - Headset: Quest2
 - Oculus Link Cable
 - VRTRAKILL 0.8.2

**Comment by whateverusername0** [comment]
well that sucks. i use a vrpatcher from https://github.com/Raicuparta/unity-vr-patcher and i don't know how it works (for me it's magic words), so i can't help you in that. The only thing i can think of is closing all unnecessary programs because it might have something to do with ram

**Comment by Kedjik** [comment]
I tried like closing everything, opening VRTRAKILL in my second OS its just not working. Maybe a new GPU issue? My card is RTX 4070 and that source didnt updated like for 3 years. I will try to use older drivers today but idk if that will work.

**Comment by Prodgidy** [comment]
did you download correct bepinex?

**Comment by Kedjik** [comment]
> did you download correct bepinex?

I downloaded the 5.4.21 version. Do i need to download another for this?

**Comment by Prodgidy** [comment]
i mean a x64 or x86 versions

**Comment by Kedjik** [comment]
I downloaded x64 im pretty sure.

**Comment by Prodgidy** [comment]
i think you should make sure that you have the correct one for your pc, if you search system info on taskbar, open system information and find system type, you can find what your computer is. 
(if your computer is x86 then download x86 version of bepinex)

**Comment by Kedjik** [comment]
I tried every single version but only x64 creates the plugin folders etc. Still gives the same errors.

**Comment by whateverusername0** [comment]
did it fix itself? 👉👈

**Comment by Kedjik** [comment]
No sadly. Tried with 0.8.4 same errors.

**Comment by whateverusername0** [comment]
unfortunate :(

**Comment by SpyroDenis** [comment]
Kedjik i have the same problem maybe its beacuse of the string "[Warning: Unity Log] <b>[SteamVR]</b> Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. OpenVR is not in your list of supported virtual reality SDKs. Add it to the list in player settings. To attempt to force OpenVR initialization call SteamVR.Initialize(true)." i looked this up on the internet but couldnt find anything maybe the developer knows something about it?

**Comment by whateverusername0** [comment]
yeah it's a [library problem](https://github.com/nesrak1/AssetsTools.NET/issues/26). can't do anything about it, sorry :(

**Comment by Kedjik** [comment]
After months of trying i figured out the problem. It was happening cuz of my windows language. If this error happens to you just switch to English. (language was Turkish before)

**Comment by whateverusername0** [comment]
holy shit, congrats
