### ISSUE TITLE
[BUG] World rotation is flipped around, with the front of the world being behind you.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#31]
**Describe the bug**
When you boot up the game with the mod, the game will always boot with the main menu *behind* the front facing point (basically always behind you). Sure you can easily fix it by just turning around, hitting recenter in steam VR, then turning back around. But this can get real confusing if you need to recenter your playspace mid-game in a level since it will always be behind you unless you do a 180 to attempt to fix it.

**Steps to Reproduce**
1. Boot up the game. That's it. lol

**Expected behavior**
When you boot the game, the menu should be the first thing you see, without needing to flip your entire playspace around 180 degrees.

**Real behavior**
The playspace is rotated by 180 degrees, thus all content is technically facing backwards, instead of forwards. 

**Media**
Can't supply media at the moment, but it's pretty explanatory as to what I mean is wrong.

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: ALVR - Wired USB
 - VRTRAKILL Version 0.8.2

**Additional context**
Just wanted to say thanks for making this mod, was real bummed out when I saw HUSKVR essentially stopped dev and i'm glad to see a successor come from it. You're doing good lad, keep up the good work.

**Comment by whateverusername0** [comment]
might be fixed in the next update, not promising anything

**Comment by whateverusername0** [comment]
fixed in the next update
