### ISSUE TITLE
[BUG] Punch is bound to the initial "Quick Swap" binding and can't be unbound, which affects charge weapons like the Core Eject Shotgun or Piercer Revolver

### ISSUE THREAD

**Issue by OctaHeart** [whateverusername0/VRTRAKILL#32]
Hello! Taking a moment to say thank you for adding in the support for rebinding all keys, it's fixed all of the issues I've had in regards to the Index's controller layout and it's made the mod 1,000x better for me (and even made the trackpad work as well). If I knew how to make an index binding for the mod then I'd do so.

There is one bug though that I have found, unsure if it's only on Index or if it's on other platforms, but the steps to reproduce are very simple at least.

-0.8.3.1
-Desktop+, XSOverlay
-Index

The default steps below have default ULTRAKILL and VRTRAKILL_Config.json settings. I didn't see an option to rebind punch in VRTRAKILL_Config.json, so I rebound all of my controls in [SteamVR to this setup here.](https://i.imgur.com/DFYHBYN.png)

STEPS TO REPRODUCE

1. In SteamVR, rebind "Alternate Fire" to the same button that your "Quick Swap / Open Weapon Wheel" button is bound to initially, while also making sure that none of the other bindings overlap with already existing bindings. 

2. Go to the Core Eject Shotgun or Piercer Revolver (Maybe also the S.R.S. cannon but I didn't bother with that one) and press and hold the button. Instead of charging, nothing happens, and sometimes, V1 punches. 

I just swapped around the A and B button bindings on my right Knuckle for the time being so it isn't any major issue for me at least.

[Video of the bug](https://youtu.be/v8vd9si-XNE) (My bindings are set to where "B" is rebound to Alt Fire which by default is bound to "Quick Swap / Open Weapon Wheel" on Valve Index)

**Comment by whateverusername0** [comment]
try rebinding alt fire to hold and not press and see if it works

**Comment by OctaHeart** [comment]
I tried setting "Alternate Shoot" to "Held (B)" [in SteamVR bindings](https://i.imgur.com/GT7IYi4.png) and it *does* allow me to start a charge, but it lets go after a couple seconds. During a recharge phase (best seen with SLAB revolver) you can press B to showcase off the punch better at least.

**Comment by whateverusername0** [comment]
same does the weapon wheel. idk how to fix that. really. it's on steamvr side now, not mine.
