### ISSUE TITLE
[BUG] Bepinex doesn't load VRTRAKILL and thus no GUI loads on main menu.

### ISSUE THREAD

**Issue by SirSnapsalot** [whateverusername0/VRTRAKILL#34]
**Describe the bug**
GUI on main menu won't appear, hands missing, and nothing shows up once in a level when I enter it via the PC.

**Steps to Reproduce**
1. Install VRTRAKILL exactly as instructed on the main GitHub page.

**Expected behavior**
Basic GUI to appear.

**Real behavior**
Nothing shows up except for the main menu. I checked the console + log file and found out that VRTRAKILL is not being loaded which is likely to be the root cause.

**Media**
Difficult to show ingame pictures, but from the Bepinex log file you can see that only UnityExplorer (which is not causing any bugs) is being loaded.
![image](https://github.com/whateverusername0/VRTRAKILL/assets/133404088/ec2dd743-b2fd-4779-b3dd-54050a6dfd59)

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software Oculus Link
 - VRTRAKILL Version 0.8.4

**Additional context**

**Comment by whateverusername0** [comment]
i can see that it doesn't load vrtrakill at all. wtf? everything should be in place. please send here your folder contents in BepInEx/plugins/VRTRAKILL, i need to check if the vrtrakill dll is actually there

**Comment by SirSnapsalot** [comment]
I checked, and nowhere in the vrtrakill folder is there a vrtrakill.dll.

**Comment by whateverusername0** [comment]
i checked releases and the dll is there. i updated latest release including the dll. i think you know where to put it

**Comment by DiamondYoshi** [comment]
well I have the DLL and the controllers and gui don't work, gamepad is also disfunctional and mouse doesn't work
