### ISSUE TITLE
[Feature request] Controller-based crosshair

### ISSUE THREAD

**Issue by SushiRoll55** [whateverusername0/VRTRAKILL#36]
I’ve noticed that the crosshair follows the VR camera direction rather than the gun’s direction. It doesn’t affect the direction that the gun shoots, but it would definitely be nice to have a functional crosshair rather than just having it in the center of view.

**Comment by whateverusername0** [comment]
that's not really a bug... i'll consider it a feature request, yea, i'll do smh about it :)
