### ISSUE TITLE
[BUG] Broken calibration screen

### ISSUE THREAD

**Issue by giulgu17** [whateverusername0/VRTRAKILL#37]
**Describe the bug**
Since the intro screen follows the camera and you select with the middle of your camera, I cannot click any button in the intro (At most I could get past the audio calibration but I had no control over it, and after that it becomes literally impossible) and the mouse doesn't work.

**Steps to Reproduce**
1. Boot up VRTRAKILL
2. Go to 0-1 and choose to do it with the intro
3. Try to calibrate

**Expected behavior**
To be able to get past the intro

**Real behavior**
Can't get past the intro

**Media**
I've attached a video of me trying to get past the intro

https://github.com/whateverusername0/VRTRAKILL/assets/66566897/32760905-aba0-4d26-993d-e83e03be49ca

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software (if using Quest): Oculus Link
 - VRTRAKILL Version: 0.8.6

**Additional context**
I haven't seen any video of people doing the intro, so it could also be that I'm just a dumbass.

**Comment by whateverusername0** [comment]
i really never tried calibrating in vr, ngl that's really weird. it's probably some thing i forgot to set to make it not move. yeah i'll release a quick fix, but for now move the bepinex folder somewhere else, calibrate and then paste it in your game folder again (basically do it without the mods)

**Comment by giulgu17** [comment]
Yeah, that's what I've done. Thank you and keep up the good work!

**Comment by whateverusername0** [comment]
Yeah, it will be fixed in the next update (0.8.7)
