### ISSUE TITLE
Really Big hands.

### ISSUE THREAD

**Issue by Travelling-doggo** [whateverusername0/VRTRAKILL#38]
**Describe the bug**
My hands and guns are big ingame

**Steps to Reproduce**
Launch VRTRAKILL.
Load into any level.
See that your gun and hands are big.

**Expected behavior**
Have normal hands.

**Real behavior**
Have big hands.

![image](https://github.com/whateverusername0/VRTRAKILL/assets/113718344/437bd93c-5f43-47a2-88f7-561bb8bd4acd)

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software (if using Quest): ALVR,
 - VRTRAKILL Version: 0.8.6

**Comment by whateverusername0** [comment]
Change your gun position to the right (if you have it centered in normal uk)

**Comment by Travelling-doggo** [comment]
> Change your gun position to the right (if you have it centered in normal uk)

Worked, thanks!
