### ISSUE TITLE
Wasn't working properly, tried to fix it, now literally nothing works.

### ISSUE THREAD

**Issue by Biggerhomie20** [whateverusername0/VRTRAKILL#43]
So Vrtrakill wasnt updating properly or something so i tried a bunch of different things and it just wasnt working and eventually i think i deleted something i wasnt supposed to so now it just launches normal ultrakill everytime

how tf can i even mess up this badly

**Comment by Biggerhomie20** [comment]
im thinking about just deleting my entire vrtrakill and redoing the steps to create one

**Comment by Biggerhomie20** [comment]
ok weird ass thing i just found while doing that
the vrtrakill config somehow got into my normal ultrakill?
seriously how tf did any of this happen

**Comment by whateverusername0** [comment]
you are a goofy.
this is not a mod issue (a bug or smh else), this is a "i fucked up and nothing works" :(
just reinstall the entire thing if you feel like it
