### ISSUE TITLE
[Feature Request] Valve index support

### ISSUE THREAD

**Issue by MrPlagueDoc3680** [whateverusername0/VRTRAKILL#45]
**Is your feature request related to a problem? Please describe.**
Currently the controls for the valve index are defaulted to the vive's controls. Now, this wouldnt be an issue, if the valve index had the same *controllers* as the vive, but it doesnt so that causes an amalgamation of weird controls that are barely functional. 
I suggest adding support to the valve index headset, it doesnt have to be full hand tracking just optimized controls.
if you can find alternative solutions, be my guest.

**Comment by whateverusername0** [comment]
I suggest buying me a valve index controllers, so i could actually map them good. Otherwise, nty :)
If you want controls done right - you gotta do it yerself.

**Comment by MrPlagueDoc3680** [comment]
I see, thanks either way. good job on the mod!
