### ISSUE TITLE
Size Rescaling

### ISSUE THREAD

**Issue by RiddleMajor** [whateverusername0/VRTRAKILL#46]
It's quite annoying when your guns are twice the size of your head. Any way to fix this without breaking the game?

**Comment by whateverusername0** [comment]
uh, do not use middle weapon position?

**Comment by whateverusername0** [comment]
so did switching the middle weapon position in the options work?

**Comment by RiddleMajor** [comment]
I use right position. But I'll try switching to middle.

**Comment by RiddleMajor** [comment]
Being on middle makes it a lot worse

**Comment by whateverusername0** [comment]
wait, so you were using the right position? my bad. check if you have a world scale set in steamvr. if it is, then disable it.

**Comment by RiddleMajor** [comment]
I still can't find world scale. Is it in steamvr settings or somewhere else?

**Comment by RiddleMajor** [comment]
It's already off. And when I try changing it, steamvr doesn't save the setting.

**Comment by RiddleMajor** [comment]
Fixed it by turning world scale down. Thank you!
