### ISSUE TITLE
[BUG] jump height and speed is abysmal

### ISSUE THREAD

**Issue by twgatorade** [whateverusername0/VRTRAKILL#47]
might or might not be related to something that i just failed to know but i just now downloaded v0.10 and i believe that i followed all the steps correctly enough for it to work, launched the game with steamvr opened and my valve index connected and re-bound all the things i felt like i needed to change, and now at the moment i try to clear the gap in the tutorial and i cant get enough height out of a jump or even a slam storage, all while the dash barely even pushes you forward where 3 dashes arent enough to get to the other side of the gap
hopefully this is a simple thing that can be fixed easily so that i dont have to worry about following instructions that im too incompetent to follow or have to study literature to explain things better

**Comment by whateverusername0** [comment]
duplicate. before opening another issue please check other closed issues to see if the problem is there and did it get solved.
in config there'll be an option to "disable movement override"; enable it and then launch the game again.
