### ISSUE TITLE
[Feature Request] Something quite simple

### ISSUE THREAD

**Issue by Ena-Shepherd** [whateverusername0/VRTRAKILL#48]
**Is your feature request related to a problem? Please describe.**
Going through the tickets to solve potential bugs, i've spotted a really big problem inside the project.
Thankfully, this problem was also experienced by others and i've figured out a really simple way to fix the fact that the owner treats every user like a dog.

**Describe the solution you'd like**
Directly solving as "Duplicate" or being a bit more respectful towards people trying to enjoy your content

**Describe alternatives you've considered**
- Forking the project
- Reporting the user

**Additional context**
Being nice costs nothing,
and if you don't want to answer tickets, please just put someone else on it and it will be much nicer for everyone.

Hope it will be solved soon.
Peace.

**Comment by whateverusername0** [comment]
yknow it gets boring and sometimes frustrating answering the same questions and solving the same problems. i'm the only person working on the project at the moment, so i can't assign anyone else.
also i'm figuring out ways to fix those bugs, i'm just telling how to not stumble upon them. everything will be fixed soon enough.
i should make a faq. and a couple tutorials. i'll be working on that this week (i think).
also reporting someone for not being nice on the internet is dumb. "thank you for your feedback. we're trying our best to improve your experience"🤓

**Comment by whateverusername0** [comment]
leaving the issue open and not responding is also a meanie thing to do. me sad. me fork and report.
