### ISSUE TITLE
Controls not working

### ISSUE THREAD

**Issue by Prodgidy** [whateverusername0/VRTRAKILL#5]
Hello, whenever i try to use any controls they dont do anything, im taking a wild guess since im not a programmer but i believe it is tied to the "VRTRAKILL_Config" as all of the inputs for it are null.
The Json:
{
  "VRSettings": null,
  "VRInputSettings": null,
  "Inputs": null
}
Thanks

**Comment by whateverusername0** [comment]
Sorry for that, I fucked something up in the config. I updated the release, it should work now

**Comment by Prodgidy** [comment]
Well the controllers on the main menu are fine and are really nice, however the controllers in game are broke (rip). The hands dont show up even when i have a gun and the place where the gun fires is always in one spot which doesn't turn with my headset turning (not using controller turning). The fist works fine tho
Im running the mod on a Oculus Rift headset which i think should be something to note haha
[Here](https://www.youtube.com/watch?v=n4f4KmXihok) is a video showing whats going on

**Comment by whateverusername0** [comment]
i think i know why his happens and i will fix that in the next patch. this issue is now closed and a new one is opened. also you can expect the bug fix coming in a few days, perhaps even tomorrow :)

**Comment by Prodgidy** [comment]
fair bro, after taking your advice i do got some feedback, first off this sh*t rocks and i love it you've done an astounding job and many shall experience dopamine because of you, there are some things tho
1. The ability to add a "no animations" type setting would be nice as I found myself getting a little disoriented when trying to fire the revolver and have it flick up
2. Having a ((easy)) way to change the vr controllers bindings would be god send as because I'm oculus rift, the dash button is right underneath the move button making very difficult to do any movement tech like dash-jumping and also getting out of sticky situations (j say easy way as I'm sure that you can do some trickery with controls in the json which would be complicated for some users)
3. Im not too sure if im just dumb on this one but i wasn't able to switch to different revolver variants. This one is just kinda a general thing that either im stoopid or its already in development.
Also this is like at end of development but it'd be funny if i could throw the mindflayer outta the stratosphere with the spawner arm in sandbox
thats the most amount of feedback i can give as i havent had too much time to play around with this, i can give more soon and ill be on the lookout for any bugs  :)

**Comment by whateverusername0** [comment]
>Having a ((easy)) way to change the vr controllers bindings would be god send  

vr controllers bindings can be easily changed via steamvr menu. i don't think i'm gonna change that. *perhaps* i'll make a launcher later but not 100% guaranteed.

>The ability to add a "no animations" type setting would be nice as I found myself getting a little disoriented when trying to fire the revolver and have it flick up

It's simply not possible atm. For some reason shooting is binded to the animator (magic ultrakill code) and if you disable the animator it will simply not reload or even get equipped.

>Im not too sure if im just dumb on this one but i wasn't able to switch to different revolver variants.

The default keybind to change weapon variations atm is F (which is by default Punch in ultrakill), so change it to E or whatever key you have in the config and everything should work

>if i could throw the mindflayer outta the stratosphere with the spawner arm in sandbox

now that's fucking epic. i'll figure out how sandbox arm works and i'll make sure to make it use controller input instead of camera one in future patches.
