### ISSUE TITLE
[BUG] Variation Switching

### ISSUE THREAD

**Issue by RavenVR** [whateverusername0/VRTRAKILL#50]
when i click button A it doesnt switch gun variation

**Steps to Reproduce**
1. idk, own a quest 2?

**Expected behavior**
To switch from sharpshooter or Piercer 

**Real behavior**
Nothing

**Other info:**
 - Headset: Quest 2
 - Intermediate software (if using Quest) Link/Air Link
 - VRTRAKILL Version most recent

**Comment by whateverusername0** [comment]
Check your keybinds both in the game and in the config. If there's a difference, that may be the source of your problem.

**Comment by RavenVR** [comment]
ive checked them but it still doesnt want to work

**Comment by RavenVR** [comment]
@whateverusername0

**Comment by whateverusername0** [comment]
Uh, what else did you check and try? This is getting interesting

**Comment by RavenVR** [comment]
nvm i fixed ith
:)

**Comment by whateverusername0** [comment]
you could atleast tell how you did it :(
