### ISSUE TITLE
VRTRAKILL won't start in VR

### ISSUE THREAD

**Issue by PootisMasta101** [whateverusername0/VRTRAKILL#51]
I installed VRTRAKILL yesterday, and got it working perfectly fine.  Completed Act 1, had a great time.  However, this morning, upon starting it in the same way as before, it just opens like regular Ultrakill, no VR or anything.  What's even weirder is that it has my VRTRAKILL save files, not the saves from the Steam release of the game.  I have absolutely no idea why this is happening or how to fix it, the only thing I can think of is to start from scratch, and I would not like to do that.

**Comment by PootisMasta101** [comment]
Scratch the part about the saves, I just started the game up again and it put my save file into the base ultrakill along side the rest of my saves?!?!  What is happening?

**Comment by whateverusername0** [comment]
Hello?
