### ISSUE TITLE
[Feature Request] Pause Button?

### ISSUE THREAD

**Issue by CricetoYT** [whateverusername0/VRTRAKILL#52]
It'd be nice to have a pause button (maybe there's one already and I'm just dumb, if so let me know lol) so I don't have to walk over to my keyboard and press escape every time I want to restart or quit to the menu. All of the buttons are currently taken up but maybe there's a way to bind holding a button for a few seconds to pause?

**Comment by whateverusername0** [comment]
there is one. i forgot to add that double tapping B (by default) will pause the game
