### ISSUE TITLE
[BUG] Cannot Start the Game

### ISSUE THREAD

**Issue by kierkat10** [whateverusername0/VRTRAKILL#53]
**Describe the bug**
So, I can start the game and see I'm falling through the tunnel (or whatever it is) and can aim with my head to the start button and whatnot. The problem is that no matter what button I press, I can't click the start button, and am stuck on the falling screen.

**Steps to Reproduce**
1. Go into the game
2. See the falling animation
3. Cannot click anything (or I just don't know what to click)

**Expected behavior**
To play VRTRAKILL and VRTRAKILL everything.

**Real behavior**
I couldn't do anything to the game.

**Media**
It's so basic that I don't think you need any screenshots. (plus I have literally no idea how to take one)

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Oculus Link
 - VRTRAKILL VERSION: 0.10

Oh, and I didn't get any error message upon starting the game for the first time, I don't know if that's not good but it happened

**Comment by kierkat10** [comment]
Nevermind, the solution was just to go into steam vr on my computer and select start from there

**Comment by whateverusername0** [comment]
☹️at least close the issue if you solved it
