### ISSUE TITLE
Endlessly falling through an empty elevator in VR

### ISSUE THREAD

**Issue by Devlyn1234** [whateverusername0/VRTRAKILL#54]
Before reporting anything, see [Common problems](https://github.com/whateverusername0/VRTRAKILL#common-issues)  
Also expect meanie things to be said (https://github.com/whateverusername0/VRTRAKILL/issues/48) (lol)

So I can see myself in ULTRAKILL, but for some reason I cannot start the game. On the computer, I can see the menu to play the game, go to options, etc, but I cannot click on those. On VR however, such a menu is not present, instead I am just endlessly falling through an elevator.

**Steps to Reproduce**
1. Copied the ULTRAKILL VR files to the game
2. Activate Steam VR and play ULTRAKILL
3. Game starts but I am endlessly falling through an elevator in VR

**Expected behavior**
Wanted the menu to show up in VR so I can play the game

**Real behavior**
No menu is present.

**Media**
If applicable, add screenshots / videos to help explain your problem.

**Other info:**
 - Oculus Quest 2
 - Virtual Desktop
 - 0.10

**Additional context**
Where button?

**Comment by Devlyn1234** [comment]
Another note is I also have no hands, I am using the oculus vive controllers.

**Comment by whateverusername0** [comment]
Are you *sure* you did everything properly? I have several reasons why this could happen:
1. You did something wrong when installing the mod
2. The mod's patcher is being goofy again (which is a performance issue) (which also shouldn't happen if you got a beefy pc that can run vr)

**Comment by whateverusername0** [comment]
Also when you try to remap vive bindings you need to set controller *raw* poses. I set them as essential because you want your controllers to get tracked in-game, right? Set them and bindings should save properly.

**Comment by Devlyn1234** [comment]
Well, issue certainly is not my computer, so my goofy self is going to reinstall the mod after purging whatever I just did. Will respond when I do so. Also thanks for the help on controller binds.

**Comment by Devlyn1234** [comment]
> Also when you try to remap controller bindings you need to set _raw_ poses. I set them as essential because you want your controllers to get tracked in-game, right? Set them and bindings should save properly.

Okay, now this is a nightmare, now the game won't even load in VR, despite the fact that I am literally selecting it in the library... Now, this is going to sound incredibly smooth brain stupid, but is there anyway you can send me the entire game with the VR properly installed considering it seems like I may have broken it more?

**Comment by whateverusername0** [comment]
Yeah unfortunately i can't to send it to you, because it'd be piracy, which might be against the rules here, idk.
You can try launching ultrakill manually (local files). A console should appear, just don't plug off your headset, because steamvr will fail to launch. In there you will see all the logs. Also if it fails at launch, in bepinex folder there should be the latest log txt file. Send it here and i'll see what i can do.

**Comment by Devlyn1234** [comment]
I do not see such a log txt file in the Bepinex folder, and along with that, no code box ever appears when trying to run ULTRAKILL.

**Comment by whateverusername0** [comment]
Meaning somethings' wrong with either your bepinex installation or w/ vrtrakill one. I have a video guide, it's above the text one; try following it instead (if you haven't done that yet)

**Comment by Devlyn1234** [comment]
> Meaning somethings' wrong with either your bepinex installation or w/ vrtrakill one. I have a video guide, it's above the text one; try following it instead (if you haven't done that yet)

So I followed the video all the way through and I am now back, stuck at the endlessly falling elevator. At least this means I can send you the log file you asked for. Have a look.
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/11772508/LogOutput.log)

**Comment by Devlyn1234** [comment]
OKAY NEVERMIND IT WORKS NOW. Thank you. Amazing mod.
