### ISSUE TITLE
[Feature Request] Movement Speed Changing

### ISSUE THREAD

**Issue by tuntor689** [whateverusername0/VRTRAKILL#58]
**Is your feature request related to a problem? Please describe.**
The movement speed, jumping, and dash distance can be really slow on higher hertz headsets. Not really a problem in non-VR mode, but according to the developer of the mod, it is a problem with the game using the Update() method which works every frame, and is unfixable. So, how about a workaround?

**Describe the solution you'd like**
Maybe in the config files (or automatically via detecting people's current framerate if you really don't want people cheating) you could be allowed to change the movement speed. It'd probably be complicated and I don't expect it happening anytime soon (hell, someone else might make a movement speed mod before it gets implemented into this mod), as there's more important stuff to fix and polish rather than something that's just a little bit of a problem, but hopefully it'd be in the 1.0 release.

**Describe alternatives you've considered**
Lowering the Hz of my headset is fine, but it's a tiny bit of a hassle having to lower it for one specific game I want to play.

**Additional context**
https://github.com/whateverusername0/VRTRAKILL/issues/42

**Comment by whateverusername0** [comment]
good idea. instead of toggling a static speed multiplier, why don't just make the multiplier dynamic? will be added in the next patch
