### ISSUE TITLE
cant transition from act 1 to act 2

### ISSUE THREAD

**Issue by grzybowy** [whateverusername0/VRTRAKILL#59]
**description**
basically when i finished act 1 and after the gabriel cutscene (disgrace humilation) i was stuck on the screen to "insert to play act 2"
it moved with my head like the hud and i couldn't press any of the buttons

**Steps to Reproduce**
1. finish act 1 (probaly on a new save)
2. go through the gabriel cutscene
3. get stuck on the screen

**Expected behavior**
i thought it would work like the title screen

**Real behavior**
it was stuck on my head an i couldn't press any of the buttons also i couldn't open the pause menu or do anything 
on my keyboard and mouse

**Other info:**
 - Headset:  Oculus Quest 2
 - Intermediate software: Oculus Link, Steam vr
 - VRTRAKILL Version 0.11.2

**Comment by whateverusername0** [comment]
will be fixed in the next patch

**Comment by whateverusername0** [comment]
gonna leave it as open to not forget to fix it (lolol)

**Comment by whateverusername0** [comment]
yea it's fixed and will be in the next update

**Comment by grzybowy** [comment]
Nice
