### ISSUE TITLE
Any possibility of quest 2 support?

### ISSUE THREAD

**Issue by Whheat** [whateverusername0/VRTRAKILL#60]
I doubt the quest 2 is strong enough but maybe quest 3/pro?

**Comment by MEGACHEB** [comment]
💀

**Comment by whateverusername0** [comment]
💀

**Comment by LoafRepositryOfStuff** [comment]
there's this funny thing called oculus link

**Comment by Whheat** [comment]
I was just curious I figured it wouldn’t work. If it did it would take quite a lot of work. Thankfully I’ll be rich enough for a legit pc soon.
