### ISSUE TITLE
Movement speed is too slow now in 11.2

### ISSUE THREAD

**Issue by TobyReid1998** [whateverusername0/VRTRAKILL#61]
I understand that your calculations were incorrect before for movement speed, but the new movement speed is far too slow as it doesn't allow you to avoid attacks and doesn't give you the feeling of how it feels to play ULTRAKILL. The previous movement speed could be considered a little too fast for some. So if you'd like to tweak it a little that would be understandable, but as it stands now it is semi unplayable in harder levels like the Gabriel boss fights and the prime sanctums.

**Comment by whateverusername0** [comment]
since 0.11.2 the player's speed is now configurable in the config. should be labeled as "multiplier" something.
