### ISSUE TITLE
[BUG] Left handed mode flips revolver

### ISSUE THREAD

**Issue by thatonep** [whateverusername0/VRTRAKILL#62]
When left handed mode is enabled, both revolver variants are offset way in front of the player and flipped to they point backwards instead of forwards. I messed around with other settings in the config but it seems like just an issue with left handed mode in general. Setting the weapon position to left to unmirror them for left handed mode also causes the HUD to get placed in a weird spot on the screen. I'm using the valve index on the latest version (0.11.2)

**Comment by whateverusername0** [comment]
i really haven't tested left handed mode, because i'm too lazy to open up the game each time :( my bad
i'll fix that and also check on the hud getting a bit quirky at night.

**Comment by Hoshi82** [comment]
Yep same issue here when trying to play left handed mode. Posted some screenshots in the flat2vr discord section of Ultrakill.

**Comment by whateverusername0** [comment]
yeah, left-handed mode is broken. i'll be focusing on it in future updates, but certainly not 0.12

srry, no compatibility for now 🤷‍♂️

**Comment by Hoshi82** [comment]
Will this be adressed in the near future?

**Comment by whateverusername0** [comment]
not yet...
