### ISSUE TITLE
[BUG] Movement based punching broken

### ISSUE THREAD

**Issue by thatonep** [whateverusername0/VRTRAKILL#63]
Ever since 0.11.2 movement based punching (with or without the new velocity based punching) has stopped working. It works in neither left or right handed mode, and no matter what i set the minimum velocity to. I tried mapping a button on my controller to punching, but whenever movement based punching was enabled, neither the keybind or the F key caused V1 to punch, but both worked when disabling movement based punching all together. I made sure the keybind was consistent in the config and game settings, I've tried with and without the new velocity punching system, so I think I've isolated the problem to movement based punching.  I'm using the valve index headset

**Comment by thatonep** [comment]
Also I know i've been leaving a lot of bug reports lately but I would just like to say that this mod is super fun and I really appreciate the work you put into solving issues and adding features.

**Comment by whateverusername0** [comment]
wdym by "stopped working"? like, it worked all fine and just stopped? pls elaborate.
also i'm gonna need more info: bepinex logs (in game/bepinex folder) and unity logs (in AppData/LocalLow/Hakita/ULTRAKILL/Player(latest).log

**Comment by thatonep** [comment]
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/11862958/LogOutput.log)
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/11862971/Player.log)
Here are the files you requested, and let me elaborate a bit more about what happens
The punch stopped working as soon as i updated to the latest version. I went in sandbox to try new features, and when i tried to test out the new velocity based punches, no matter what I did the game would not register the punch and just wave around my palm. I tested and it didn't hurt enemies either on both hands. I messed around with the config after that, disabled the new punch system which still didn't work, and the only way I was able to throw a punch was if I disabled movement based punching and used a controller bind to punch. Essentially, updating was what made the punches stop working, not like a certain duration of time passing or anything

**Comment by whateverusername0** [comment]
have you checked the changelog? you now have to hold the punch button and *then* fling your arm. if it works lmk

**Comment by whateverusername0** [comment]
i've checked the logs and there's nothing specifically weird happening.

**Comment by thatonep** [comment]
Oh you're right, I was pressing the button and swinging my arm but not both simultaneously ;-;. I misunderstood the changelog and thought that was how you used the blast part of the knuckleblaster not just punch in general. mb
