### ISSUE TITLE
[Feature Request] I have Index controller binds but don't know how to send them to you

### ISSUE THREAD

**Issue by thatonep** [whateverusername0/VRTRAKILL#64]
I redid the controller bindings for index because the defaults suck (cuz you don't have index controllers). I'm not entirely sure how you want me to send them to you since steam workshop doesnt work for non steam games added (as far as I'm aware). I can create a diagram or list of the bindings if that helps? I'm mostly just writings this cuz I have controls I like and want to submit them somehow

**Comment by whateverusername0** [comment]
idk someone sent them in another issue but ig you could ping me on discord and we can figure it out

**Comment by whateverusername0** [comment]
the small chat box is clickable btw

**Comment by thatonep** [comment]
My discord username: thatone_p msg me when you can
