### ISSUE TITLE
[BUG] NameHere

### ISSUE THREAD

**Issue by golubxd** [whateverusername0/VRTRAKILL#67]
can't punch on windows mixed reality. worst of all - punching isn't even binded by default! i had to make my own bind for punching and after all i couldn't punch - it worked with huge delay, and i can't bind it on the trigger.

just make it on the left trigger by default

i would expect that punching would be on the left trigger by default, but jumping was binded for the left trigger

 headset: [HP Windows Mixed Reality]
 version 0.11.2

**Comment by whateverusername0** [comment]
you could've reopened this issue :(, wait a minute
