### ISSUE TITLE
[BUG] NameHere

### ISSUE THREAD

**Issue by BEEP-BOOP-jpg** [whateverusername0/VRTRAKILL#68]
Before reporting anything, see [Common problems](https://github.com/whateverusername0/VRTRAKILL#common-issues)  
Also expect meanie things to be said (https://github.com/whateverusername0/VRTRAKILL/issues/48) (lol)

**Describe the bug**
Application folder:
C:/Program Files (x86)/Steam/steamapps/common/ULTRAKILL
There should be 'ULTRAKILL_Data'
folder next to the executable

**Steps to Reproduce**
1. No idea, I just copied everything in the ultrakill folder, and followed steps.
**Expected behavior**
for it to work

**Real behavior**
Death.

**Media**
If applicable, add screenshots / videos to help explain your problem.

**Other info:**
 - Headset: [Oculus Quest 2]
 - Intermediate software Virtual Desktop
 - VRTRAKILL Version [e.g. 0.8]

**Additional context**

**Comment by whateverusername0** [comment]
i might be dumb but i don't understand a single word you say
if it's an installation error pls join the discord and ask ppl for help there, heck even ping me, but *this* is a wendys (bug report section)
the chat thingie on the main page is clickable, ty for understanding
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/d4a6b576-d642-41ec-bbb1-a09413d00626)
