### ISSUE TITLE
i dont know how to change controlls Dash and Move is on the same Hand 

### ISSUE THREAD

**Issue by Ventras26** [whateverusername0/VRTRAKILL#69]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (ex. I'm always frustrated when *this*)

Dash on Quest Controlles feels a bit off since u dash with the Thumb but u also MOVE with the thump its nearly impossible to Dash and also Move in a certain direction at the same time

**Describe the solution you'd like**

the list VRTRAKILL_Config.json is nice but its not easy to understand 
am i supposed to just exchange things in there to my liking
how exactly does it work 
maybe put the names of the Buttons there so people know where to put which command if that is even a possibillity cause im to afraid to try in all honesty 

in all honesty thank you sooo much for making this 
no hate or anything this is MEGA awesome 
 
 but this is something that kinda keeps me from playing it in VR for now

**Comment by whateverusername0** [comment]
config is the mod settings
to change controller buttons bindings you need to go into the steamvr menu and change them there

**Comment by Ventras26** [comment]
oh dear 0o since i never played Ultrakill id be doing that completly blind 
but thanks i guess i can maybe ask some friends how to bind it the best way

**Comment by whateverusername0** [comment]
cool
