### ISSUE TITLE
[BUG] Cant swap arms

### ISSUE THREAD

**Issue by omertalhaunal** [whateverusername0/VRTRAKILL#70]
**Describe the bug**
The Change Arm action on steamvr does nothing

**Steps to Reproduce**
1. Launch VRTRAKILL with Oculus Quest 2
2. Try using right grip to change weapon
3. Nothing happens
4. Try resetting the action to another button that you have tested
5. Nothing happens

**Expected behavior**
Arm to change

**Real behavior**
Arm didnt change

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Oculus Airlink
 - VRTRAKILL Version: 0.11.2

**Comment by whateverusername0** [comment]
has to be a keybind problem. check the keybinds in config and make sure they match with the game ones

**Comment by omertalhaunal** [comment]
Will try when i get Home if it doesnt Work i'll Update this response

**Comment by omertalhaunal** [comment]
Im terribly sorry for forgetting this

yeah it was my own dumbassnes

the mod is amazing btw i really enjoyed it
thanks for the help
and i wish you good luck on devoloping
