### ISSUE TITLE
[BUG] cannot complete fishing level

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#71]
you can't throw the bombfish in the fishing level to get past the first area, and all fish caught float to the end of the rod and just hover there indefinitely until you hit quickswap, replaying the whole "you caught a [insert fish here]" thing. 

**Steps to Reproduce**
1. get any fish

**Expected behavior**
to be able to progress

**Real behavior**
fish do not behave as intended, and you cannot use a bombfish to progress

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Virtual Desktop
 - VRTRAKILL Version: 0.11.2

**Comment by whateverusername0** [comment]
i'll take a look into that

**Comment by whateverusername0** [comment]
i don't see any problem in getting fish, really.
the footage is from 0.12-pre, i haven't made *any* changes to the way how fish or fishing rod behaves

https://github.com/whateverusername0/VRTRAKILL/assets/113782077/03880ff3-462f-426b-867f-479b83a91818

idk how to help you with your problem. srry :(
