### ISSUE TITLE
[BUG] revolver and feedbacker disappearing

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#72]
**Describe the bug**
The meshes of hands and revolver disappear if looking up too far, even though they're still clearly in my fov

**Steps to Reproduce**
1. use the base revolver and feedbacker
2. tilt head upward while keeping hands at the same height
3. look down without moving head
4. weapons disappear while still in view

**Expected behavior**
weapon stays visible

**Real behavior**
weapon disappears

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Virtual Desktop
 - VRTRAKILL Version: 0.11.2

**Additional context**
having experience with this issue in unity, I'd recommend disabling "toggle mesh visibility when off screen" or whatever equivalent there may be on the hand and weapon meshes. this will not affect the performance, as it's very few meshes with low res textures.

**Comment by whateverusername0** [comment]
it'll be fixed in the next update

**Comment by darnerfloi** [comment]
awesome, thanks

**Comment by ak-sergeev** [comment]
In version 0.17 for some reason this issue appeared again
