### ISSUE TITLE
[Feature Request] if no weapons are equipped, allow both hands to parry (copy left hand actions onto right hand)

### ISSUE THREAD

**Issue by diddlyono** [whateverusername0/VRTRAKILL#73]
lemme just fuckin like parry and punch my way through levels fuck guns bro
like let whiplash be usable on both hands and shit like that yknow
being able to equip 2 different arms at the same time (like feedbacker on right, knuckleblaster on left) would be cool

kinda like this
![image](https://github.com/whateverusername0/VRTRAKILL/assets/67235885/49887e33-ecfb-402f-95e1-c85e159a71c1)

**Comment by whateverusername0** [comment]
i'll think about it

**Comment by diddlyono** [comment]
swag 👍

**Comment by whateverusername0** [comment]
i've thought about it and i've decided to not add that. i want the mod to feel as vanilla as possible, without any *new* features that the game doesn't have.
