### ISSUE TITLE
[Feature Request] better rotation 

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#74]
I've been having issues with moving around my playspace as I play, as you do not rotate around your head, instead rotating around the center of the playspace, and your collision stays at the same point as well. It makes you phase into walls and stuff. I'm here to ask for head based artificial turning, and for the collision to follow the head, to make the experience that much better.

**Comment by whateverusername0** [comment]
i've already tried doing that, but it never works as intended. i guess i'll try to do smth abt it again

**Comment by whateverusername0** [comment]
also big thanks for actually reporting actual bugs, you're a godsend

**Comment by darnerfloi** [comment]
Oh, no problem. I really enjoy the mod and wanna try and help with it whatever ways I can. I may not have much experience with coding itself but I know a lot about unity's systems. I've made a few hundred vrchat avatars over a couple years, so I know a decent bit regarding meshes, rigging, and collision! I can recognize issues in certain areas, and if I see them I'll be sure to let you know.

**Comment by whateverusername0** [comment]
> It makes you phase into walls and stuff.

it's being worked on. expect it coming out in the next minor update
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/c0e5e728-f37b-4175-b027-74587d14be64)
