### ISSUE TITLE
[Feature Request] Custom textures 

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#76]
Hey, this is just a smaller thing that's in no way necessary, but would be really cool to see: allowing the player to change out the playerbody textures for their own. I don't know how difficult it would be to allow for that to happen, but if it's in the realm of possibility I'd love to see it happen. I've used Ultraskins with the mod before the playerbody was added and it did change the hands, so I was thinking why not the whole thing?

**Comment by whateverusername0** [comment]
Yeah sure, when 0.12=> comes out. I was planning on adding v2 model as well.

**Comment by darnerfloi** [comment]
Awesome, can't wait to see the final build of 0.12, I have no doubt in my mind that it's going to be amazing.

**Comment by whateverusername0** [comment]
sorry, change of plans. won't be coming out in the nearest future.
