### ISSUE TITLE
[Feature Request] offhand crosshair

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#77]
okay last request I think, I've been playing with the headlook based whiplash since I first got the mod due to aiming it with the offhand being a nightmare. A separate crosshair attached to the offhand for the whiplash would help a ton.

**Comment by whateverusername0** [comment]
I wish i could add it, but differentiating between those crosshairs will be another nightmare. Two evils.
I'll think about it, but for now there's no plans to work on it.
