### ISSUE TITLE
[BUG] snap turning breaks the game 

### ISSUE THREAD

**Issue by darnerfloi** [whateverusername0/VRTRAKILL#81]
**Describe the bug**
Snap turning being enabled causes the game to crash on startup 

**Steps to Reproduce**
1. Enable snap turning in the config
2. Start up vrtrakill 
3. Watch it stop responding and crash

**Expected behavior**
Functional snap turning 

**Real behavior**
An inability to play the game at all

**Other info:**
 - Headset: Oculus Quest 2 
 - Intermediate software: Virtual Desktop 
 - VRTRAKILL Version: 0.11.2  and 0.12 preview both have the issue

**Comment by whateverusername0** [comment]
This is weird, considering snap turning doesn't do anything more than smooth turning does. Only with a bigger delay. I'll check it out

**Comment by whateverusername0** [comment]
fixed in the next release :)
