### ISSUE TITLE
One controller 

### ISSUE THREAD

**Issue by Liskanyme** [whateverusername0/VRTRAKILL#83]
I didn't know how to comment so I just created an issue, I wanted to ask that if a person has only one controller, will he be able to play?  This can be implemented by enabling the "middle hand" 
I just recently started using github, so there will be no tags

**Comment by whateverusername0** [comment]
imagine walking, jumping, shooting, hand swapping, grappling and other things ALL on a single controller. ofc you wouldn't be able to play like that.

**Comment by Liskanyme** [comment]
> imagine walking, jumping, shooting, hand swapping, grappling and other things ALL on a single controller. ofc you wouldn't be able to play like that.

I was just wondering, besides, there are some controllers sold that have enough buttons and don’t actually have a pair, at least I’ve seen those, I’m not talking about some small controller like the ones that are usually used
