### ISSUE TITLE
[BUG] When completing a level and falling down the shaft, as soon as the ui that shows you your time, kills, and style just freezes as soon as the credit counter shows up, i can still select my arms in that screen aswell

### ISSUE THREAD

**Issue by mionosprime** [whateverusername0/VRTRAKILL#84]
I have to go to my keyboard and press the esc key to pull up the pause menu and press exit level on that screen, When the screen usually shows up you should normally see the score, but it just freezes. The headset i use is a Quest Two, the program is virtual desktop. and the ultrakill version is patch 13B

**Comment by whateverusername0** [comment]
do you use any other mods beside vrtrakill? also please send the logs (they are located in ULTRAKILL/BepInEx & USERPROFILE%\AppData\LocalLow\Hakita\ULTRAKILL\Player.log) and a short video showcasing the problem. until then i have no idea how to help you

**Comment by mionosprime** [comment]
![image_2023-08-12_014849410](https://github.com/whateverusername0/VRTRAKILL/assets/142059190/bfecc305-5a94-4916-8f49-5eaf4e843020)
I couldn't send a video bc of how big the file was but heres a picture. it keeps falling and i can move and change my arms.
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/12326770/Player.log)
 
[Player-prev.log](https://github.com/whateverusername0/VRTRAKILL/files/12326771/Player-prev.log)
these are the log files. i have some mods installed including HydraDynamics, Plugin configuator, UFG Weapons, the middle finger punch, Ultracoins, UMM, Ultrakill Tweaker, and custom arms. im not sure if theres a fix for this issue.

**Comment by whateverusername0** [comment]
ULTRATweaker is the root of your issue. vrtrakill is not compatible with _a lot_ of mods, so be careful when adding something onto it.
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/6d1373f3-b298-4237-8401-a36268fa82dc)
