### ISSUE TITLE
[BUG] game crashes whenever i go to punch something

### ISSUE THREAD

**Issue by Vobasan** [whateverusername0/VRTRAKILL#85]
Before reporting anything, see [Common problems](https://github.com/whateverusername0/VRTRAKILL#common-issues)  
Also expect meanie things to be said (https://github.com/whateverusername0/VRTRAKILL/issues/48) (lol)

**Describe the bug**
whenever i press trigger and punch forward with my left hand, my game just full on closes.

**Steps to Reproduce**
1. Do this
2. Do that
3. See error

**Expected behavior**
I expected to be able to punch lol

**Real behavior**
game crashed

**Media**
If applicable, add screenshots / videos to help explain your problem.

**Other info:**
 - Headset: Quest 2
 - Intermediate software (if using Quest) Virtual Desktop
 - VRTRAKILL Version [0.11.2]

**Additional context**

**Comment by whateverusername0** [comment]
please send the logs (they are located in ULTRAKILL/BepInEx & USERPROFILE%\AppData\LocalLow\Hakita\ULTRAKILL\Player.log), your VRTRAKILL_Config file and a short video showcasing the problem, because right now i have zero context on what's happening. until then i have no idea how to help you

**Comment by Vobasan** [comment]
> please send the logs (they are located in ULTRAKILL/BepInEx & USERPROFILE%\AppData\LocalLow\Hakita\ULTRAKILL\Player.log), your VRTRAKILL_Config file and a short video showcasing the problem, because right now i have zero context on what's happening. until then i have no idea how to help you
[LogOutput.log](https://github.com/whateverusername0/VRTRAKILL/files/12327614/LogOutput.log)
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/12327623/Player.log)
(Config File settings):  "Gameplay Settings": {
    "Player movement multiplier (speed, jump power, etc.)": 0.72,
    "Enable first-person 4-S camera (broken)": false,
    "Controller-based shooting": {
      "Enable controller-based shooting": true
    },
    "Movement-based punching": {
      "Enable movement-based punching": true,
      "Required speed to punch (default: 7.5f)": 0.0,
      "WHIPLASH: Disable controller aiming (enable camera aim)": false,
      "Enable coin throwing from hand (not from the gun)": true,
      "Enable punch direction detection by velocity (instead of what's infront of you)": true
    },
    "Hand Gestures (unused)": {
      "Enable hand gestures": true,
      "Replace pointing gesture with a middle finger": false
    },
    "VR Body": {
      "Enable VRIK": true
    }
  },
  "Input Settings": {
    "Input": {
      "Deadzone (from 0 to 1)": 0.4,
      "Snap turning": false,
      "Snap turning angles": 45.0,
      "Smooth turning speed": 300.0,
      "Enable Controller Haptics (Vibration)": true
    },
    "Keybinds": {
      "Fire": "MouseLeft",
      "Alternative Fire": "MouseRight",
      "Punch": "F",
      "Jump": "Spacebar",
      "Slide": "LeftControl",
      "Dash": "LeftShift",
      "Last weapon used": "Q",
      "Change weapon variation": "E",
      "Iterate weapon (weapon scroll)": "MouseScroll",
      "Swap hand": "G",
      "Whiplash": "R",
      "Escape (pause, etc.)": "Escape",
      "Slot 1": "1",
      "Slot 2": "2",
      "Slot 3": "3",
      "Slot 4": "4",
      "Slot 5": "5",
      "Slot 6": "6",
      "Slot 7": "7",
      "Slot 8": "8",
      "Slot 9": "9",
      "Slot 0": "0"
    }
  },
  "Controller Settings": {
    "Use controller-based UI interaction (broken)": false,
    "Controller Lines": {
      "Draw controller lines": true,
      "Initial transparency (from 0 to 1)": 0.4,
      "End transparency (from 0 to 1)": 0.1
    },
    "Hands": {
      "Swap hands (left-handed mode)": false,
      "Enable arms (VRIK) (unused)": true
    }
  },
  "View Settings": {
    "VR UI": {
      "Enable standard HUD (replaces classic hud)": true,
      "HUD Size (from 0 to 0.1)": 0.0625,
      "Crosshair distance": 8.0
    },
    "Desktop View (for recording, etc.)": {
      "Enable Desktop View": true,
      "World View FOV": 90.0,
      "UI View FOV": 45.0
    }
  }
}

https://github.com/whateverusername0/VRTRAKILL/assets/110250766/fa26aa27-eace-4caf-84e8-4f89989824bd


here you go. it wouldn't let me upload the entire config file so i just copy and pasted it. i hope thats okay.

**Comment by whateverusername0** [comment]
many thanks. i see no problem in the config nor in the logs, expect that you're drawing controller lines for no reason and it flooded them making reading the entire thing a pain.
try these things when possible:
disable UMM (move it out of the plugins folder) (vrtrakill works without UMM),
disable movement-based punching.

lmk if any of this fixes your problem

**Comment by Vobasan** [comment]
ok so removing UMM didn't fix anything, but disabling the movement based punching works. however I really want to find a way to fix the movement based punching

**Comment by whateverusername0** [comment]
it seems broken. i'll be checking on it asap. count it fixed in the next release

**Comment by whateverusername0** [comment]
i lied. will be fixing it in minor patches. leaving it open

**Comment by Vobasan** [comment]
i messed around with the config file a bit and it fixed itself. I forget what exactly i changed, but the punching works now

**Comment by whateverusername0** [comment]
what
