### ISSUE TITLE
[BUG] Not sure if it's a bug, but I walk as slow as a grandpa with arthiritis.

### ISSUE THREAD

**Issue by kai3109** [whateverusername0/VRTRAKILL#86]
I literally walk slow as hell. I had to beat v2 by standing still and hoping for luck. Dashing is not great either, because it's just as slow as walking. Any fixes?

**Comment by whateverusername0** [comment]
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/03f898de-55e7-4af4-a971-8fa4f251f5c4)
