### ISSUE TITLE
NO CONFIG FILE

### ISSUE THREAD

**Issue by bobishereformods** [whateverusername0/VRTRAKILL#89]
whenever i install everything correctly step by step i even followed the video and text guide (btw im on index) and when i install it and try to launch it it gives an error and says cant initialize player and more error shit and whatever and im assuming its because i did not cnfig my controls so i went to the config directory on your page and there was no config file so i cant do anything thats the only thing im missing but again it could be something else causing this issue but im pretty sure its because of the absence of config.

**Comment by whateverusername0** [comment]
please send the logs (they are located in ULTRAKILL/BepInEx & USERPROFILE%\AppData\LocalLow\Hakita\ULTRAKILL\Player.log), because "more error shit" says nothing

**Comment by bobishereformods** [comment]
[Message:   BepInEx] BepInEx 5.4.21.0 - ULTRAKILL (4/27/2023 10:43:28 AM)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete



but this is not my problem my problem is the error saying    Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.

and there is still no config

**Comment by whateverusername0** [comment]
it didn't find any plugins to load + unity is screaming at you meaning something is wrong w/ your uk/bepinex install, not the mod.
double check everything you've done, reinstall bepinex, reinstall ultrakill *and* bepinex, oil yourself, etc.

**Comment by bobishereformods** [comment]
mkay

**Comment by bobishereformods** [comment]
ive done what youve said its not working also when i use other mods they work perfectly fine but this one in particular just doesnt work

**Comment by bobishereformods** [comment]
IT WORKS NOW THNKS MUCH
