### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by buzzlesthebee** [whateverusername0/VRTRAKILL#91]
I changed punch velocity to half, and disabled VR avatar, however, the game completely ignored my changes. Any clue on what's happening? I saved the file, and it's in the correct location.

**Comment by whateverusername0** [comment]
vel-based punch is broken. don't use it.
uh it's actually already fixed in the next release, so...

**Comment by buzzlesthebee** [comment]
What about the VR model?

**Comment by whateverusername0** [comment]
afaik it doesn't crash anything

**Comment by buzzlesthebee** [comment]
No, the config does not work. I am trying to disable the character model but the game uses default vrtrakill config instead of the changes that I made to the file.
