### ISSUE TITLE
Configuration file in plugins>VRTRAKILL doesn't work.

### ISSUE THREAD

**Issue by buzzlesthebee** [whateverusername0/VRTRAKILL#92]
Whenever I adjust the mod's config, nothing changes. I'm using Visual Studio, and saved the file, reopened it and the changes are there, but the mod doesn't care. wtf?

**Comment by whateverusername0** [comment]
are you sure that nothing prevents the mod from opening the config?

**Comment by whateverusername0** [comment]
bro.

**Comment by whateverusername0** [comment]
hi hello?
