### ISSUE TITLE
[BUG] Punching causes game to crash

### ISSUE THREAD

**Issue by Gigabitten** [whateverusername0/VRTRAKILL#93]
**Describe the bug**
When I punch, the game crashes. When I say crashes, I don't mean hangs or whatever, I mean it unceremoniously stops existing. 

**Steps to Reproduce**
Open game.
Hold left trigger.
Move hand forward.

**Expected behavior**
Game doesn't crash.

**Real behavior**
Game crashes.

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Oculus Link, obviously
 - VRTRAKILL Version 0.12

**Additional context**
The only log I could find (LogOutput.log) only has this:

[Message:   BepInEx] BepInEx 5.4.22.0 - ULTRAKILL (4/27/2023 2:40:14 PM)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] Loaded 1 patcher method from [VRPatcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   Console] Backing up 'E:\SteamLibrary\steamapps\common\ULTRAKILL\ULTRAKILL_Data/globalgamemanagers'...
[Info   :   Console] Backup already exists.
[Info   :   Console] Begin epic conversion from ULTRAKILL to VRTRAKILL...
[Info   :   Console] Using ClassData file from 'E:\SteamLibrary\steamapps\common\ULTRAKILL\BepInEx\patchers\classdata.tpk'
[Info   :   Console] Epic conversion from ULTRAKILL to VRTRAKILL is complete.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [VRPatcher.Patcher]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [VRTRAKILL 0.12]
[Message:   BepInEx] Chainloader startup complete

Which doesn't seem to be much help.

If there are other log files I'm missing, I'll gladly provide them. It seems like I'm a common use case, so there must be more context to be had, but I'm unsure what to look for.

**Comment by Gigabitten** [comment]
oh no. I just found that this issue has existed before and apparently "messing around with the config files" did the trick whatever that means. here's the logs you asked for in the previous case
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/12517259/Player.log)

**Comment by Gigabitten** [comment]
oh yeah and this (changed file extension - .txt not supported by github? wtf?)
[VRTRAKILL_Config.txt](https://github.com/whateverusername0/VRTRAKILL/files/12517264/VRTRAKILL_Config.txt)

**Comment by whateverusername0** [comment]
the fix should come out with the next release, just, yknow, i always forget to publish it and keep adding on features that are too buggy to release.

**Comment by whateverusername0** [comment]
expect it rolling out +-today

**Comment by Gigabitten** [comment]
Cool, highly appreciated!
