### ISSUE TITLE
[BUG] Aim problems with the pistol

### ISSUE THREAD

**Issue by Gigabitten** [whateverusername0/VRTRAKILL#94]
**Describe the bug**
Can't do core snipes or even just long-range shots with the pistol properly. The obvious method is to use the crosshair to aim, but it has a certain distance from the player. Attempting to account for this by instead using the pistol's iron sights so that the barrel, the crosshair, and the target form a straight line reveals that the pistol's aim is slanted slightly to the right of what makes sense; this is probably to account for the fact that in the normal game, the pistol should shoot straight, but V1 holds it tilted a bit inward. 

This problem is not present for the railcannon. Which is great, since nukes are very fun. But shots with the pistol at a long enough distance for this to be a problem are common enough for me at least that not being able to align the barrel, crosshair, and target is a big downside.

**Steps to Reproduce**
1. Shoot pistol.
2. See that the bullet doesn't go straight out of the barrel.

**Expected behavior**
It shoots straight.

**Real behavior**
It shoots crooked.

**Other info:**
 - Headset: Quest 2
 - Intermediate software (if using Quest): Oculus Link
 - VRTRAKILL Version: 0.12.1

**Comment by whateverusername0** [comment]
i already know about that problem, it's just that i'm too lazy to mess around w/ offsets n such. but now ig i mustn't ignore that :(

**Comment by whateverusername0** [comment]
should be fixed in the next major release
