### ISSUE TITLE
[BUG] Dash jumping doesn't give as much momentum, further slide eats dash charges

### ISSUE THREAD

**Issue by Gigabitten** [whateverusername0/VRTRAKILL#95]
**Describe the bug**
Dashes have the right distance, but if you dash and then jump, you're supposed to carry a lot of speed; slide hopping still works, but dash jumping to, for example, start a slide hop chain doesn't work at all. Instead, you just go very slowly. 

**Steps to Reproduce**
1. Dash.
2. Immediately afterward, jump.

**Expected behavior**
You go pretty far.

**Real behavior**
You go basically nowhere. Not sure if it's further than without the dash, but it's not very far.

**Media**
https://github.com/whateverusername0/VRTRAKILL/assets/24787321/c655303c-18a4-499a-971e-514854c7ef4b

Other info:

    - Headset: Quest 2
    - Intermediate software (if using Quest): Oculus Link
    - VRTRAKILL Version: 0.12.1

**Comment by whateverusername0** [comment]
yeah, i guess it doesn't add more speed when dash jumping. i'll do smth about it

**Comment by Gigabitten** [comment]
Update: found a workaround in letting go of dash before jumping (not necessary in base game) and found a further problem which may be related, which is that further slide hops tend to eat dash charges for no reason.

**Comment by whateverusername0** [comment]
should be fixed in 0.15.2
